### ISSUE TITLE
ESP32: I2C broken by c9e0ad2ac21c26820f04f95d42307a3d53e20ebd

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#1007]
At least on ESP32 the mentioned commit ( https://github.com/esp-rs/esp-hal/commit/c9e0ad2ac21c26820f04f95d42307a3d53e20ebd ) breaks I2C

Need to test on other targets

**Comment by bjoernQ** [comment]
Tested on all the others and it works there - so it's most probably just some issue with the ESP32 SVD

**Comment by jessebraham** [comment]
Closed by #1009
