### ISSUE TITLE
Light-/deep-sleep support for ESP32-C6

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#1028]
This will serve as a tracking issue for light-/deep-sleep support for the ESP32-C6.

Work in this area is already underway:

- [x] https://github.com/esp-rs/esp-hal/pull/974
- [x] https://github.com/esp-rs/esp-hal/pull/918
- [x]  Wakeup sources other than EXT1
- [ ] Various system state save/restore for light sleep

Please feel free to use this issue for any related discussion. I will add relevant pull requests above as they are opened.

**Comment by jessebraham** [comment]
#918 has been merged. I know this isn't feature-complete yet, @bugadani are you able to summarize what's left to do? Or should we just close this issue now?

**Comment by bugadani** [comment]
There are two main areas that I ignored so far:
 - wakeup sources other than EXT1
 - various system state save/restore for light sleep

**Comment by bjoernQ** [comment]
We now have working basic light-sleep and a few more wakeup-sources. I _think_ for remaining features we should have separate issues as needed instead of keeping this issue open forever

**Comment by bjoernQ** [comment]
I suggest closing this issue and creating new issues as needed for retaining CPU state etc. when we see a need for it. Feel free to re-open if you disagree
