### ISSUE TITLE
Remove the `embedded-hal@0.2.x` trait implementations when able

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#1034]
I think, once we're able, we should rip out the old trait implementations and remove the `eh1` feature, implementing the latest stable traits by default.

Prerequisites:

- [ ] Stable `1.0.0` releases of the relevant `embedded-hal-*` packages (expected December 28th, 2023)
- [ ] [embedded-hal-compat](https://github.com/ryankurte/embedded-hal-compat) updated to use stable releases

I will take care of this at some point in the new year, just wanted to get an issue open for tracking progress and to allow for any discussion regarding this topic.

**Comment by bjoernQ** [comment]
Would definitely make things more maintainable. I think there are some traits which didn't made it into 1.0 e.g. Adc but that one has its issues so we probably should just provide our own (better) implementation

**Comment by jessebraham** [comment]
> I think there are some traits which didn't made it into 1.0 e.g. Adc but that one has its issues so we probably should just provide our own (better) implementation

Yeah I think for the most part, the traits that do not have analogues in the `1.0.0` release are not use heavily (or at all) by driver code, so I'm not sure we're losing out on much there. In general I think we need to improve our APIs when not using trait methods anyway, so this will likely push us to do so for at least a few peripherals.

**Comment by MabezDev** [comment]
I think that maybe removing 0.2 impls isn't the best idea, for one embedded-hal-compat can be quite finicky to work with. Secondly, https://github.com/ryankurte/embedded-hal-compat/pull/32#issuecomment-1952591174 would suck.

**Comment by jessebraham** [comment]
> I think that maybe removing 0.2 impls isn't the best idea, for one embedded-hal-compat can be quite finicky to work with. Secondly, [ryankurte/embedded-hal-compat#32 (comment)](https://github.com/ryankurte/embedded-hal-compat/pull/32#issuecomment-1952591174) would suck.

Are you suggesting we keep the `0.2.x` and `1.0.0` implementations _forever_?

**Comment by MabezDev** [comment]
Maybe not forever, but until the majority of the ecosystem drivers is on eh1. I think it's worth keeping around for now at least.
