### ISSUE TITLE
esp32h2: default XTAL is 32mhz

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#1127]
![image](https://github.com/esp-rs/esp-hal/assets/6977289/be30184a-627c-4b31-b79d-973713179da0)

This doesn't seem to be causing problems right now, but the fact we don't have a feature for it, in esp-hal or espflash means we were probably not aware of this.

**Comment by jessebraham** [comment]
As a side note, which has been raised before (more than once), it's incredibly unclear how to map from the clock diagrams in the TRMs to our clock code. Would be _really_ helpful having some documentation here, as clocks seem to be randomly selected from both the left and right edges of the diagram.

**Comment by jessebraham** [comment]
Now that we've eliminated the XTAL frequency features I think we can close this? Unless I'm missing something the H2 seems to be using this frequency now.

@MabezDev please re-open if I am mistaken.

**Comment by MabezDev** [comment]
The 32MHZ xtal case isnot yet handled so we need to keep this open.

**Comment by jessebraham** [comment]
Can you elaborate please? What actually needs to be done? The XTAL frequency in boot defaults is 32MHz, where else does this need to be changed?

**Comment by MabezDev** [comment]
I spent most of today trying to remember why I wanted to not forget about this, it was this issue I wanted to test: https://github.com/esp-rs/esp-hal/issues/766 and I think the xtal was the issue. We can close this now.
