### ISSUE TITLE
Broken build on esp-hal-common 0.15

### ISSUE THREAD

**Issue by vlad-onis** [esp-rs/esp-hal#1186]
Started a test project using `cargo generate esp-rs/esp-template` and selected esp32c3. After generation a simple cargo check fails as in the picture below. Note that esp32c3-hal v 0.14 works without problems. I just attached 2 pictures but the errors are endless.

LE: This happens as well if I follow the no-std-training to just start the hello world. Same errors. (https://esp-rs.github.io/no_std-training/02_3_repository.html)

<img width="938" alt="Screenshot 2024-02-19 at 23 43 14" src="https://github.com/esp-rs/esp-hal/assets/107788332/b9b08459-11a2-48b3-bece-5c67212ca742">
<img width="929" alt="Screenshot 2024-02-19 at 23 43 21" src="https://github.com/esp-rs/esp-hal/assets/107788332/6ed05fa5-3180-46d3-8bdf-74275e08d485">

**Comment by vlad-onis** [comment]
> I just generated a fresh project and it builds? Have you setup your environment correctly? Take a look at https://esp-rs.github.io/book/installation/riscv.html

Are you on macos as well?

**Comment by vlad-onis** [comment]
I followed that I have the target installed

**Comment by MabezDev** [comment]
That was on Linux, but I've just done the same on MacOS and it works there too. Take a look at the link I gave you, and or paste the full output from cargo in a gist.

**Comment by vlad-onis** [comment]
https://gist.github.com/vlad-onis/c552df6602db7ba876309cea575b3853

**Comment by MabezDev** [comment]
https://github.com/esp-rs/esp-hal/blob/567a44f28c41ac42199b928062135b7e47ec4b15/esp-hal-common/src/gpio.rs doesn't contain any lines with `esp32c3_hal`. You've corrupted the crates.io registry on your machine. I would run `rm -rf ~/.cargo/registry` to solve this.

**Comment by vlad-onis** [comment]
It felt like a completely dirty state on my machine. Tried the above and it seems to work. Gotta admin I was scared to delete the folder in case there are configs I might mess up. I was about to do a test with docker tmw since now it's very late. I'm happy however it's fixed today. Ty very very much for looking into this!
