### ISSUE TITLE
Support embassy-usb on ESP32-S2 and ESP32-S3

### ISSUE THREAD

**Issue by Dominaezzz** [esp-rs/esp-hal#1191]
Whilst this crate supports `usb-device` (which is not `async`), it'd be really cool if it also supported the async `embassy-usb`.

Some efforts have begun [here](https://github.com/embassy-rs/embassy/issues/2494).

**Comment by Dominaezzz** [comment]
These registers should be accessible by index. The 0 at the end can vary from 0 to 6.
```
pub type DOEPCTL0 = crate::Reg<doepctl0::DOEPCTL0_SPEC>;
pub type DOEPINT0 = crate::Reg<doepint0::DOEPINT0_SPEC>;
pub type DOEPTSIZ0 = crate::Reg<doeptsiz0::DOEPTSIZ0_SPEC>;
pub type DOEPDMA0 = crate::Reg<doepdma0::DOEPDMA0_SPEC>;
pub type DOEPDMAB0 = crate::Reg<doepdmab0::DOEPDMAB0_SPEC>;
```

**Comment by bjoernQ** [comment]
Probably the PACs should get patched to collect these registers into arrays. We use https://github.com/rust-embedded/svdtools for patching SVDs in https://github.com/esp-rs/esp-pacs
