### ISSUE TITLE
TIMG timers should support period mode

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#123]
Currently we only support target mode.

Period mode could be potentially useful e.g. `esp-wifi` currently uses period mode of SYSTIMER and since the HAL lacks that functionality it accesses the registers directly.

**Comment by MabezDev** [comment]
@bjoernQ I think this is already done for TIMG timers? When used with the e-h timer traits they are used in periodic mode? Please correct me if I'm wrong :D.

**Comment by bjoernQ** [comment]
🤔 seems you are right 👀  .... but probably it shouldn't be like that? 

i.e. by default, it should be one-shot and we should have an "into_periodic" function (like systimer) to turn it into periodic mode?

**Comment by bjoernQ** [comment]
Sounds like the best way to go - then it's aligned with systimer 👍

**Comment by bjoernQ** [comment]
Ohh you are right
