### ISSUE TITLE
AES seems to only support 128-bit keys

### ISSUE THREAD

**Issue by jeamland** [esp-rs/esp-hal#1234]
In the various device-level HAL implementations for the AES peripheral there is a flexible size for the key via the [`AesFlavour`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/src/aes/mod.rs#L214) trait.

Unfortunately this is not available to the user as the [`Aes::process`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/src/aes/mod.rs#L153) method defines its `key` argument as `&[u8; 16]` which means we're unable to pass anything other than a 128-bit key in.

Is this an intentional limitation?

**Comment by jessebraham** [comment]
> Is this an intentional limitation?

The AES driver was contributed by a community member, so it's not reasonable to expect all features to be implemented. Would love to see a PR for this, though.
