### ISSUE TITLE
DMA: Add option to configure psram block size

### ISSUE THREAD

**Issue by seijikun** [esp-rs/esp-hal#1235]
In the current DMA abstraction, I miss the option to configure the PSRAM blocksize.
In esp-idf, this can be set to 3 possible values:
- `#define GDMA_LL_EXT_MEM_BK_SIZE_16B (0)`
- `#define GDMA_LL_EXT_MEM_BK_SIZE_32B (1)`
- `#define GDMA_LL_EXT_MEM_BK_SIZE_64B (2)`

This is the corresponding `esp-idf` method:
```c
/**
 * @brief Set DMA TX channel memory block size
 * @param size_index Supported value: GDMA_LL_EXT_MEM_BK_SIZE_16B/32B/64B
 */
static inline void gdma_ll_tx_set_block_size_psram(gdma_dev_t *dev, uint32_t channel, uint32_t size_index)
{
    dev->channel[channel].out.conf1.out_ext_mem_bk_size = size_index;
}
```

I would've loved to add it myself, but after some time of looking at `esp-hal'`s DMA abstraction, I had to capitulate to the architecture, sorry.

**Comment by Dominaezzz** [comment]
I'd argue this is largely solved by #2161 , even if all drivers don't support the buffer traits yet.
