### ISSUE TITLE
SpiDma Half duplex is hard to use

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#1236]
The signatures for [write and read](https://docs.rs/esp32s3-hal/latest/esp32s3_hal/spi/master/dma/struct.SpiDma.html#method.read) require `self` which means we have to dance around moving it. Ideally, it should be possible with `&mut self`.

cc: @bjoernQ I believe you implemented this initially

**Comment by bjoernQ** [comment]
Yes I think we can make things much simpler this way
