### ISSUE TITLE
Don’t forget to upgrade the defmt version in esp-backtrace and esp-println.

### ISSUE THREAD

**Issue by danclive** [esp-rs/esp-hal#1263]
As follows:

```
cargo run --release
    Updating crates.io index
error: failed to select a version for `defmt`.
    ... required by package `esp-hal v0.16.0`
    ... which satisfies dependency `esp-hal = "^0.16.0"` of package `code v0.1.0 (/path/code)`
versions that meet the requirements `=0.3.6` are: 0.3.6

the package `defmt` links to the native library `defmt`, but it conflicts with a previous package which links to `defmt` as well:
package `defmt v0.3.5`
    ... which satisfies dependency `defmt = "=0.3.5"` of package `esp-backtrace v0.11.0`
    ... which satisfies dependency `esp-backtrace = "^0.11"` of package `code v0.1.0 (/path/code)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the `links = "defmt"` value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `defmt` which could resolve this conflict
```

Could we make the defmt version more flexible, for example, by removing the ‘=’?

**Comment by jessebraham** [comment]
Sorry for the oversight, we'll get this fixed ASAP.

For context, you can see the discussion around pinning the dependency here:  
https://github.com/esp-rs/esp-hal/pull/1249#discussion_r1516291250

I originally did not want to pin the version for this exact reason, however unfortunately knurling-rs does _not_ provide MSRV guarantees on patch releases, so without pinning the version it's possible for our MSRV guarantees to be broken by a patch release of `defmt`, which IMO is not really acceptable.

I'm happy to hear potential alternatives to this approach as well. I guess we will need to be a little more on the ball with regards to our libraries and `defmt`.
