### ISSUE TITLE
variant usage

### ISSUE THREAD

**Issue by burrbull** [esp-rs/esp-hal#1304]
Looks like you've found a hole in svd2rust API safety.

https://github.com/esp-rs/esp-hal/blob/1846543873e884e5c5d8f20635acc6ef714cd2fb/esp-hal/src/assist_debug.rs#L44

**Comment by jessebraham** [comment]
This seems unrelated to the HAL so I am going to close it. If I am mistaken please feel free to add more information and reopon.

**Comment by burrbull** [comment]
`variant` should not be used for writing raw bytes. There is `bits` for this. Safe or unsually `unsafe` depending on `writeConstrains` values.
This is a hole that variant is possible to use there.
Trying to fix it with https://github.com/rust-embedded/svd2rust/pull/825
