### ISSUE TITLE
Many drivers are dependent on eh2 traits

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#1317]
We already were aware of twai, see #1123, but upon switching to eh1 by default, I had to hack in this commit: https://github.com/esp-rs/esp-hal/pull/1313/commits/121dca7e2201ef59657a5f3bd476612aaecc80a1. All of these fixme's and now public functions exist because they were _only_ usable via the eh02 traits. 

They need fixing so that

* They work without any eh feature
* The new APIs are documented

## tracking

- [x] #1355
- [x] #1367
- [x] #1372
- [x] #1391
- [x] https://github.com/esp-rs/esp-hal/pull/1392
- [x] https://github.com/esp-rs/esp-hal/pull/1386

**Comment by jessebraham** [comment]
@MabezDev is working on GPIO, I have opened PRs for the remaining peripherals.

**Comment by jessebraham** [comment]
If we've missed anything please let me know but otherwise this appears to be complete.
