### ISSUE TITLE
It's seemingly impossible to only run HIL in merge queues and also have it be a required check

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#1328]
It's possible I'm missing something here, but I've read a fair amount of documentation and I'm still struggling to come up with a solution for this. Hopefully I am wrong and this is possible, though.

AFAICT, setting the HIL jobs as "required" when merging into `main` means they must ALSO run in the PR before it is eligible for the merge queue. This is not what we want, we want HIL to run _in merge queue only_ and be required to pass.

I would appreciate if somebody could investigate this, I've already spent way more of my life fighting with GHA than I'd like to admit.

**Comment by jessebraham** [comment]
I guess one possible solution might be something like this (I have no idea if it will work or not):

We can use conditionals (i.e. `if: ...` in a job/step) and try to find a way to determine if we're in merge queue or not (maybe some git ref, or something else, I don't know how this will work). If we _are_ in the merge queue we run the HIL tests. If we _are not_ in the merge queue, we have dummy jobs for each real HIL job that just always succeed.

(I kind of hate this but I don't know how else to do it)

**Comment by jessebraham** [comment]
Okay, I've added a (hopefully) temporary workaround in #1331, however I would still like to investigate a better solution. For the time being though, we at least have things working as we'd like them to for the most part.

**Comment by MabezDev** [comment]
The temporary solution ended up being okay as we now check that the HIL tests build in before merging, so I think we can close this?

**Comment by jessebraham** [comment]
There are still a lot of footguns and I wouldn't close this personally probably, but your call.

**Comment by jessebraham** [comment]
I guess what we're doing for now works, so will close this.
