### ISSUE TITLE
Add HIL tests for all peripherals which are practical to test

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#1334]
For now, let's use the table from https://github.com/esp-rs/esp-hal/issues/809#issuecomment-1999308797:

> I've gathered a list of the `esp-hal` modules and how hard/easy I think it would be to test those (take it with a grain of salt as I may have misevaluated some). Also, some modules can't be tested, or it does not make sense:
 
 * [x]  aes 
     * [x]  DMA - https://github.com/esp-rs/esp-hal/pull/1426
     * [x]  Non- DMA - https://github.com/esp-rs/esp-hal/pull/1297 and https://github.com/esp-rs/esp-hal/pull/1423
 * [ ]  analog -
 * [ ]  assist_debug -
 * [x]  clock -https://github.com/esp-rs/esp-hal/pull/1425
 * [x]  delay - https://github.com/esp-rs/esp-hal/pull/1415
 * [x]  ecc - https://github.com/esp-rs/esp-hal/pull/1418
 * [x]  gpio -
 * [ ]  hmac -
 * [x]  i2c -https://github.com/esp-rs/esp-hal/pull/2023
 * [x]  i2s - https://github.com/esp-rs/esp-hal/pull/1635 
 * [x]  lcd_cam - https://github.com/esp-rs/esp-hal/pull/1834
 * [ ]  ledc -
 * [ ]  mcpwm -
 * [ ]  otg_fs -
 * [ ]  parl_io -
 * [x]  pcnt - https://github.com/esp-rs/esp-hal/pull/1746
 * [ ]  rmt -
 * [x]  rom - https://github.com/esp-rs/esp-hal/pull/1417
 * [x]  rsa
    * [x] Blocking https://github.com/esp-rs/esp-hal/pull/1414
    * [x] Async https://github.com/esp-rs/esp-hal/pull/2002
 * [ ]  rtc_cntl -
 * [x]  sha - https://github.com/esp-rs/esp-hal/pull/1422
 * [ ]  spi   
    * [ ]  Half duplex -
    * [x]  Full duplex
    * DMA    
       * [x]  Half duplex - https://github.com/esp-rs/esp-hal/pull/1782
       * [x]  Full duplex - https://github.com/esp-rs/esp-hal/pull/1443
 * [x]  systimer - #1979
 * [ ]  timer -
 * [ ]  trace -
 * [x] #1912
 * [x]  uart 
    * [x] blocking
    * [x] async
 * [ ]  usb_serial_jtag - https://github.com/esp-rs/esp-hal/pull/1961

**Comment by MabezDev** [comment]
One reference for the peripherals is the list @SergioGasquez created here: https://github.com/esp-rs/esp-hal/issues/809#issuecomment-1999308797

**Comment by SergioGasquez** [comment]
I will be working on RSA

**Comment by SergioGasquez** [comment]
I will be working on CRC

**Comment by SergioGasquez** [comment]
Working on SHA

**Comment by SergioGasquez** [comment]
Working on clock monitoring

**Comment by JurajSadel** [comment]
I'm currently stuck with usb-serial-jtag, I will work on debug-assist next.

**Comment by SergioGasquez** [comment]
I will also try to add `aes_dma` and improve the current `aes` test to cover all the modes.

**Comment by Dominaezzz** [comment]
I want to write a HIL test for the `LCD_CAM` but there's not enough loopback pin connections. At the moment there's only two, any chance I could get two more (at least on the S3)?
The alternative is going through the GPIO matrix (which would be ideal I suppose, less faff to run the tests) but that'll need #1662 .

**Comment by SergioGasquez** [comment]
> At the moment there's only two, any chance I could get two more (at least on the S3)?

How many connected pins would you need? Feel free to suggest any pins that you would like to get connected, see https://github.com/esp-rs/esp-hal/issues/1332#issuecomment-2059093479 which might be helpful.

**Comment by Dominaezzz** [comment]
4 total pairs. A clock pin, a data pin, and two ctrl pins.

According to https://github.com/esp-rs/esp-hal/tree/main/hil-test:
- GPIO2 and GPIO4 are connected.
- GPIO5 and GPIO6 are connected.

I suppose a strategic choice for two more pairs would be:
- GPIO1 and GPIO21. (GPIO1 is the only (excluding strapping pins) pin with the RTC_I2C function).
- GPIO43 and GPIO45. (GPIO43 is U0TXD pin)

My strategy there was to connect a pin with a specific function to another pin with no functions.
This is an S3 only choice, as the LCD_CAM only exists there.

**Comment by SergioGasquez** [comment]
Awesome, I'll try to get those pins connected in the upcoming days. On the ESP32-S3, the following would be added:
- GPIO1 and GPIO21 are connected.
- GPIO43 and GPIO45 are connected.

**Comment by SergioGasquez** [comment]
@Dominaezzz, our S3 self-hosted runner already has the [connections we discussed](https://github.com/esp-rs/esp-hal/pull/1680/files#diff-664e59b846c463197e118cb6f9345a3fa069cf48be5945ba460fe6e2ad159ed5R89-R90).

**Comment by jessebraham** [comment]
As discussed in our team meeting today, it would be nice to come up with some method of testing the TWAI peripheral, whether this be via loopback, external tranciever, or some other solution.

**Comment by bugadani** [comment]
We can maybe tick systimer after https://github.com/esp-rs/esp-hal/pull/1979

**Comment by Dominaezzz** [comment]
Now that we've got #2128 those extra S3 connections can be removed, as they now get in the way of finding dummy pins. The LCD_CAM HIL test works without the extra connections atm.

**Comment by bugadani** [comment]
Yeah those are biting me as well

**Comment by jessebraham** [comment]
This is going to be an eternal issue, there will always be new things to test and new devices are released and new use cases/APIs arise, so I am going to close this and we can open individual issues for peripherals as the need arises.
