### ISSUE TITLE
INT_CLR bits

### ISSUE THREAD

**Issue by burrbull** [esp-rs/esp-hal#1353]
This is the only place in `hal` where `clear_bit()` is used.
https://github.com/esp-rs/esp-hal/blob/d5abc3fc85749b80bb47f0a12990f5134d14cbee/esp-hal/src/lcd_cam/lcd/i8080.rs#L393
Does it do anything?
Is not those fields are `writeOneToClear`?

**Comment by bjoernQ** [comment]
Oh yes - it's W1TC so clearing shouldn't have any effect

cc @Dominaezzz

**Comment by Dominaezzz** [comment]
Ah yeah that's a bug

**Comment by burrbull** [comment]
After some thoughts I already not sure these bits should be described as W1TC as they clears **other** register.
I even don't see how to correctly describe it in SVD as [`modifiedWriteValues`](https://docs.rs/svd-rs/latest/svd_rs/modifiedwritevalues/enum.ModifiedWriteValues.html) does not have "write 1 to trigger" variant.
Same for corresponding `ST` registers.

**Comment by Dominaezzz** [comment]
Out of ignorance, how else is W1TC supposed to work? I can't imagine one would write to a register to clear the same register. Also how would one set the register? Do you have an example of this behaviour?

**Comment by burrbull** [comment]
> I can't imagine one would write to a register to clear the same register. Also how would one set the register?

You are right although writing 0 to this register does not change anything, this is not W1TC as writing 1 to it changes another register.
So I don't see how to describe it correctly in terms of SVD.

**Comment by bjoernQ** [comment]
Seems the definition in CMSIS-SVD and ESP32-TRMs are a bit different

CMSIS-SVD

![image](https://github.com/esp-rs/esp-hal/assets/5682593/8e37d233-2a21-4640-9775-7dd21b76cbb7)


TRM

![image](https://github.com/esp-rs/esp-hal/assets/5682593/aa1795fb-c4fe-4bdf-9ac6-7ab2209c0f18)

In  the SVDs we should follow their terminology
