### ISSUE TITLE
Asynchronously awaiting an interrupt with embassy.

### ISSUE THREAD

**Issue by Frostie314159** [esp-rs/esp-hal#1383]
Hi, I wanted to ask, if it's possible to `await` an interrupt when using `embassy`.

**Comment by MabezDev** [comment]
This sounds like an XY problem, what's your end goal?

**Comment by Frostie314159** [comment]
I'm trying to await a hardware interrupt from the wifi PHY.

**Comment by bjoernQ** [comment]
You can have a look at the async drivers in esp-hal. Basically, you'll need a future which can use AtomicWaker like here: https://github.com/esp-rs/esp-hal/blob/256d7198f9dc176f011914f6fca0d4b137f19bcc/esp-hal/src/rmt.rs#L1106-L1143

In the interrupt handler you can wake the waker: https://github.com/esp-rs/esp-hal/blob/256d7198f9dc176f011914f6fca0d4b137f19bcc/esp-hal/src/rmt.rs#L1292

**Comment by Frostie314159** [comment]
Looks great, thanks! Maybe I'll build an abstraction around this, so it can be used for any interrupt.

**Comment by jessebraham** [comment]
I don't believe there is any actionable work here, so I'm going to close this issue. Feel free to open a new issue or discussion if you have any other questions or problems :)
