### ISSUE TITLE
Remove the `split` extension traits

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#1401]
Initially suggested by @brainstorm, thanks for feedback!

I'm pretty sure we don't need them anymore, and they create confusion in documentation because it's a trait method.

- [x] GPIO Extension - only used internally anyways
    - https://github.com/esp-rs/esp-hal/pull/1496
- [x] SYSTEM Extension - no longer needed as its always called SYSTEM, we can just have `SystemParts` (bike shed the name) take `SYSTEM` in the constructor.
    - https://github.com/esp-rs/esp-hal/pull/1428
    - https://github.com/esp-rs/esp-hal/pull/1495

**Comment by jessebraham** [comment]
Thanks, meant to open an issue for this but forgot. I actually have a local branch from some time back where I had refactored away the `SYSTEM.split()` bits, I will try to revive it.

**Comment by jessebraham** [comment]
With #1428 now merged, once #1495 has been merged then the work on `SYSTEM` will be complete. Will look into the GPIO extension trait next, which should close this issue.
