### ISSUE TITLE
Remove the `#[interrupt]` macro

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#1407]
Following up from #1063 we need to:

- [x] Remove the macro from esp-hal-macros
- [ ] Document how users can still install handlers by default by using `#[no_mangle]` or `#[export_name = ""]`
    - Maybe we don't want to document this?
- [ ] Document upgrade paths from `#[interrupt]` to `#[handler]`

**Comment by bjoernQ** [comment]
> Document how users can still install handlers by default by using #[no_mangle] or #[export_name = ""]

Maybe we shouldn't document that. I will most probably just do that in esp-wifi but if users do that for an interrupt which gets taken over by an async driver they might have a bad time debugging that? Explaining all that (and maybe additionally explaining `::interrupt::bind_interrupt`) is probably a bit overwhelming for most users and others can figure things out on themselves.

**Comment by jessebraham** [comment]
#1409 probably closes this? @bjoernQ proposed a migration guide which we can use for the next release, and I think, at least for now, maybe not talking about this potential `#[no_mangle]`/`#[export_name]` foot gun is probably for the best 😅

**Comment by jessebraham** [comment]
Gonna close this, feel free to re-open if needed.
