### ISSUE TITLE
embassy time missing from Cargo.toml

### ISSUE THREAD

**Issue by Firstyear** [esp-rs/esp-hal#1429]
https://github.com/esp-rs/esp-hal/blob/main/examples/src/bin/embassy_hello_world_systimer.rs#L16 relies on embassy-time, but it's not present in https://github.com/esp-rs/esp-hal/blob/main/esp-hal/Cargo.toml

**Comment by MabezDev** [comment]
It's an example, so it can be found in the examples `Cargo.toml`: https://github.com/esp-rs/esp-hal/blob/da3375bbe47dcb659353b909fbc556a74bb64cda/examples/Cargo.toml#L16

**Comment by Firstyear** [comment]
I think I read the wrong Cargo.toml then, that's my fault.
