### ISSUE TITLE
SystemTime::new_async() can't be found

### ISSUE THREAD

**Issue by Firstyear** [esp-rs/esp-hal#1430]
https://github.com/esp-rs/esp-hal/blob/main/examples/src/bin/embassy_hello_world_systimer.rs#L41 uses new_async, but the set of features in the example leads to "function or associated item not found in `SystemTimer<'_>"

**Comment by MabezDev** [comment]
We have an examples readme: https://github.com/esp-rs/esp-hal/tree/main/examples which explains how to run the examples. In short, we use an xtask subcommand to build and enable the correct features. In this case, `cargo xtask run-example examples esp32c3 embassy_hello_world_systimer` builds and runs as expected.
