### ISSUE TITLE
Missing feature in system timer example

### ISSUE THREAD

**Issue by Firstyear** [esp-rs/esp-hal#1431]
https://github.com/esp-rs/esp-hal/blob/main/examples/src/bin/embassy_hello_world_systimer.rs#L41 depends on feature "embassy-integrated-timers" but it's not documented.

**Comment by MabezDev** [comment]
We actually use the generic timers feature for all examples, as not all chips have enough integrated timers to run all examples, see: https://github.com/esp-rs/esp-hal/blob/da3375bbe47dcb659353b909fbc556a74bb64cda/examples/src/bin/embassy_hello_world_systimer.rs#L9
