### ISSUE TITLE
Problems building with embassy async support for esp32s3

### ISSUE THREAD

**Issue by rickpayne** [esp-rs/esp-hal#1435]
Trying to get a very simple async example working on esp32s3, and can't get past this error:

```
undefined reference to `_embassy_time_schedule_wake'
``` 

This makes me thing that I'm not specifying a feature correctly. This is what I'm trying to compile:

```rust
use embassy_executor::Spawner;
use embassy_time::{Duration, Timer};
use esp_backtrace as _;
use esp_hal::{
    clock::ClockControl,
    delay::Delay,
    embassy,
    peripherals::Peripherals,
    prelude::*,
    timer::TimerGroup,
};


#[embassy_executor::task]
async fn run() {
    loop {
        esp_println::println!("Hello world from embassy using esp-hal-async!");
        Timer::after(Duration::from_millis(1_000)).await;
    }
}


#[main]
async fn main(spawner: Spawner) {
    esp_println::println!("Init!");
    let peripherals = Peripherals::take();
    let system = peripherals.SYSTEM.split();
    let clocks = ClockControl::boot_defaults(system.clock_control).freeze();

    let timg0 = TimerGroup::new(peripherals.TIMG0, &clocks);
    embassy::init(&clocks, timg0);

    spawner.spawn(run()).ok();

    loop {
        esp_println::println!("Bing!");
        Timer::after(Duration::from_millis(5_000)).await;
    }
}
```
I can't get the examples to build, as that just reports:
```
  examples git:(v0.16.1) cargo xtask run-example esp-hasl esp32s3 hello_world
error: -Zbuild-std requires --target
```

I believe the xtensa toolchain is installed correctly, as I can build and run  non-async rust code on the esp32s3. The problems start when I try to introduce embassy / async. What have I missed?

**Comment by bjoernQ** [comment]
Easiest and recommended way to run examples from the repository is using the `xtask`: https://github.com/esp-rs/esp-hal/tree/main/examples#running-examples

It should also show the features activated to run the example like this
```
[2024-04-15T08:01:23Z INFO  xtask]   Features: embassy,embassy-time-timg0,embassy-executor-thread,embassy-generic-timers
```

It might still be a bit unobvious what dependencies are needed. You can probably start with the example's dependencies found here: https://github.com/esp-rs/esp-hal/blob/main/examples/Cargo.toml and remove things which seem to be unrelated/unnecessary.

We plan to add support for embassy in https://github.com/esp-rs/esp-template but we are not there, yet
