### ISSUE TITLE
De-duplicate and generally improve examples

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#1436]
Prior to HIL testing, our examples were serving a dual purpose, both demonstrating use of the HAL and testing/verifying the functionality. With HIL testing now available, we should focus our examples on using the hardware, not proving out the drivers.

There are also a number of examples specific to third-party trait packages, e.g. all the `eh1_` prefixed examples. We should rework our examples to demonstrate only the applicable driver(s), the trait packages should be irrelevant here.

Additionally, we should try to better comment and just generally improve examples as able.

**Comment by bjoernQ** [comment]
> ... and just generally improve examples as able

I think some of the examples are really tests (especially the crypto-accelerators but also others). These are better turned into HIL tests. (But t.b.h. I can't imagine how an interesting example of using a crypto-accelerator might look like)

Some tests could be more interesting if there would be some console output
