### ISSUE TITLE
All timer's that have a `now` function should return a useful type

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#1450]
Most currently return a `u64`, which means nothing without the context of how often it increments etc.

**Comment by bjoernQ** [comment]
Somewhat related to #1139 (actually if there wasn't the ESP32 it probably would be the same 🤔 )

**Comment by jessebraham** [comment]
This should be closed with the completion of #1479, whenever that may be, so going to close this in favour of that issue.
