### ISSUE TITLE
ESP32-C3 Direct-Boot: All Examples get restarted by Watchdog

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#149]
On ESP32-C3 all the examples get restarted by a watchdog. Pretty sure it wasn't always like that. Not figured out yet which change is causing this.

**Comment by jessebraham** [comment]
CC @gustavonihei

**Comment by gustavonihei** [comment]
@bjoernQ I am not able to reproduce this issue on the `main` branch. I've just executed the `hello_world` application on the **ESP32-C3-DevKitM-1**, both in **debug** and **release** builds, and it prints "Hello world!" without restarting:
![image](https://user-images.githubusercontent.com/38959758/184898007-408b50ba-db7a-4c59-b4e3-359b5c67d71f.png)
