### ISSUE TITLE
i2c peripheral is not using a repeated start condition for `write_read()`

### ISSUE THREAD

**Issue by liebman** [esp-rs/esp-hal#1490]
A logic analyser shows that a stop condition followed by start condition is currently being issued instead of the repeated start.

Both [embedded-hal](https://docs.rs/embedded-hal/latest/embedded_hal/i2c/trait.I2c.html#method.write_read) and [embedded-hal-async](https://docs.rs/embedded-hal-async/latest/embedded_hal_async/i2c/trait.I2c.html#method.write_read) specify that `write_read()` uses a repeated start condition.

Some devices like the [veml7700](https://www.vishay.com/docs/84286/veml7700.pdf) require a repeated start. See Fig. 4 - I2C Bus Timing for Receive Word Command Format on page 4.

**Comment by bjoernQ** [comment]
Probably the best thing to do would be to support  https://docs.rs/embedded-hal/latest/embedded_hal/i2c/trait.I2c.html#tymethod.transaction - for the embedded-hal trait the provided methods will use it and things should be fine
