### ISSUE TITLE
Cant assign IO (esp_hal::gpio::IO) to a struct or static for later use

### ISSUE THREAD

**Issue by Gibbz** [esp-rs/esp-hal#1510]
I'm not sure if i am doing this the right way. But I want to store the reference to IO in my function to either a struct, or static so that I can use it from other modules to access the gpio pins. When I try to assign it it complains that the method does not implement copy....

If i comment out the i2c code it works, but I assume ill have a similar issue in the future....

Edit: the same happens with peripherals if I try to store that too.

Error:
```
use of partially moved value: `io`
partial move occurs because `io.pins.gpio2` has type `GpioPin<esp_hal::gpio::Unknown, 2>`, which does not implement the `Copy` trait
```

minimal example:
```
use esp_hal::gpio::IO;

pub struct System {
    pub io: IO,
}


impl System  {
    pub fn init() -> Self {
        let peripherals = Peripherals::take();
        let system = peripherals.SYSTEM.split();
        let clocks = ClockControl::boot_defaults(system.clock_control).freeze();
        let myio = IO::new(peripherals.GPIO, peripherals.IO_MUX);

        // Initialize and configure I2C0
        let mut i2c0 = I2C::new_async(
            peripherals.I2C0,
            myio.pins.gpio3,
            myio.pins.gpio2,
            100u32.kHz(),
            &clocks,
        );
        Self {
            io: myio, // <-- error here **
        }
    }
}

```

**Comment by MabezDev** [comment]
Hey @Gibbz! Rust is stopping you from moving a value in which some of its sub fields have been moved. To combat this you should also move the pins you want for later and store those in the struct instead :).
