### ISSUE TITLE
Rwdt feeding doesn't seem to work

### ISSUE THREAD

**Issue by i404788** [esp-rs/esp-hal#1534]
Hey there,

I'm using async/embassy with some code that may panic but is allowed to restart so I thought I'd use RTC_watchdog for this (since the regular watchdog requires timergroup which is already used for embassy). but it seems like feeding the watchdog doesn't work. I used the example code with inside the loop:

```rust
        critical_section::with(|cs| match RWDT.borrow_ref_mut(cs).as_mut() {
            Some(watchdog) => {
                println!("Feeding...");
                watchdog.feed()
            }
            None => unreachable!(),
        });
```

I can see it feeding but it still triggers after the timeout period (2 seconds in my case). I'm using ESP32S3.

**Comment by jessebraham** [comment]
Thanks for the issue, sorry for the delay in getting to it. Turned out to be a simple solution thankfully, so this should be fixed in our next release (which I'm planning to publish next week).
