### ISSUE TITLE
Is the SPI0 peripheral usable?

### ISSUE THREAD

**Issue by jvatic** [esp-rs/esp-hal#1552]
I'm trying to connect to an Spi device (a sharp memory display) over `SPI0`, but `esp_hal::spi::master::Spi::new` doesn't accept anything other than `SPI2` or `SPI3`. Am I missing something here, or is the `SPI0` peripheral not implemented yet?

**EDIT:** Clarification: this is for an ESP32S3 board.

**Comment by playfulFence** [comment]
In `esp32s3` SPI0 and SPI1 controllers are primarily reserved for internal use to communicate with external flash and PSRAM memory and SPI2/SPI3 are general purpose SPI controllers. 

This pattern is repeated on almost all chips, so yes, `SPI2` and `SPI3` should be used for normal master-slave communication.

**Comment by jessebraham** [comment]
I've actually been wondering whether renaming the SPI peripherals in our PACs to be more consistent was a mistake. Perhaps reverting to `SPIMEM{0,1}` and `GPSPI{2,3,n}` would make things a bit more clear? Not sure, just something I've been thinking of.

cc @bjoernQ @MabezDev

**Comment by jvatic** [comment]
Ah, thanks! (Looks like I'd have known that pretty quick if I'd been looking at the [hardware manual](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/hw-reference/index.html), but a quick note in a doc comment or something might be helpful)

**Comment by bjoernQ** [comment]
> I've actually been wondering whether renaming the SPI peripherals in our PACs to be more consistent was a mistake. Perhaps reverting to `SPIMEM{0,1}` and `GPSPI{2,3,n}` would make things a bit more clear? Not sure, just something I've been thinking of.
> 
> cc @bjoernQ @MabezDev

Maybe keeping SPI{2,3,..} and renaming 0/1 to SPIMEM would be an option 🤔 but most probably a hint in the docs would help more
