### ISSUE TITLE
Fix the crates.io doc link

### ISSUE THREAD

**Issue by ophilli** [esp-rs/esp-hal#1553]
https://crates.io/crates/esp-hal-common currently links to https://docs.rs/esp-hal-common/

It seems it should instead link to https://docs.esp-rs.org/esp-hal/

**Comment by jessebraham** [comment]
The `esp-hal-common` package as been retired and is no longer receiving updates. `esp-hal` is the new name of the package.

**Comment by ophilli** [comment]
Can you update https://crates.io/crates/esp-hal-common to indivate that it is deprecated? It is confusing that it was last updated 4 months ago but has an invalid link to docs.rs
