### ISSUE TITLE
esp-ieee802154: Low power receive example?

### ISSUE THREAD

**Issue by Timmmm** [esp-rs/esp-hal#1558]
Would it be possible to write an example of how to do a "sleepy" receiving device that wakes up periodically and maintains synchronisation with a mains-powered device? I know that's how BLE works; I don't know too much about IEEE 802.15.4 but I assume the same mechanisms are used with it, e.g. for Thread.

Is that actually possible using this API?

**Comment by MabezDev** [comment]
As @bjoernQ mentioned, this should be tracked in the thread implementation.
