### ISSUE TITLE
`gpio::Output::new` still have plain bool argument

### ISSUE THREAD

**Issue by KortanZ** [esp-rs/esp-hal#1569]
@bjoernQ  Really excited to have #1542 which have improved GPIO so much, thank you for your awesome work. While after a glance, I've noticed that in this refactoring, `gpio::Output::new` has plain bool argument instead of `Level`. Is this by design or just an omission?

**Comment by bjoernQ** [comment]
Thanks for the kind words! The remaining bool in the constructor is an oversight - it should take a `Level`

**Comment by JurajSadel** [comment]
@KortanZ I've started working on a GPIO-refactor "cleanup" PR (some examples in docs still have the old API, for example). I want to just double check if you are working on replacing bools with Level so we are not working on the same thing :)

**Comment by KortanZ** [comment]
@JurajSadel I've not started yet, planning start on weekends because of busy work days. Glad to see someone have already working on this. Really thank you for making things perfect. :D
