### ISSUE TITLE
esp-println: compile time module level log filtering 

### ISSUE THREAD

**Issue by rhomber** [esp-rs/esp-hal#1578]
Why not just model it from `env_logger` and send the output to the UART? The filtering that is provided by the standard log crates is really good. I'm just not sure why there's custom handling here for all the unrelated stuff vs. just working on channeling the output of how logging normally works? I'd just honor the regular env variable names too and set any internal ones you need based on them. Consistency would be awesome. Just a thought.

**Comment by lure23** [comment]
@rhomber Would you be interested in collab on the esp-println design? 

I had a look at the code, due to a separate issue, and think basing it more on what `logger` provides would be worth a go! 

Note: I am still new to Rust on embedded.
