### ISSUE TITLE
Explore replacing `libwpasupplicant.a` with a pure Rust implementation

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#1602]
This should be a non-default feature (i.e. defaulting to the precompiled `libwpasupplicant.a`)

It seems feasible to do this and might give some benefits (like better compile-time optimizations, compile time feature selection, better integration with esp-hal). It will most probably only offer a subset of functionality

Downsides might be that this code won't be battle-tested. However, we can have a look at the [CVEs](https://www.cvedetails.com/vulnerability-list/vendor_id-12005/product_id-29296/W1.fi-Wpa-Supplicant.html) and see if anything potentially might apply. Due to reduced functionality and the use of Rust many of those probably won't apply

Resources
- https://github.com/kelvincheung/lw_supplicant
- https://github.com/espressif/esp-idf/tree/master/components/wpa_supplicant
- https://fuchsia.googlesource.com/fuchsia/+/refs/heads/main/src/connectivity/wlan/lib/rsn
- IEEE Std 802.11™-2020

**Comment by MabezDev** [comment]
This won't be on our roadmap anytime soon, but we can always revisit this in the future.
