### ISSUE TITLE
20 timer callback slots may not be enough for C6

### ISSUE THREAD

**Issue by bugadani** [esp-rs/esp-hal#1614]
I'm getting this error:

`[WARN] - Failed to set timer function 40824b98`

The set of features I have enabled on esp-wifi are as follows, so I don't have BLE and coex enabled (meaning the library should be limited to 20 timers)

```
features = [
    "phy-enable-usb",
    "ps-max-modem",
    "wifi",
    "async",
    "embassy-net",
    "tcp",
    "dns",
    "ipv4",
    "dhcpv4"
]
```

**Comment by MabezDev** [comment]
These queues are now heap allocated.
