### ISSUE TITLE
multiple definition of malloc, calloc, and free when used together with other crates providing them

### ISSUE THREAD

**Issue by noahbliss** [esp-rs/esp-hal#1618]
Hey! I use another crate which wraps some C code. That crate and esp-wifi both seem to rely on the C functions listed in the title. When both crates are used, the compiler dies of an aneurysm. Any ideas on possible solutions? Could this be added as a feature perhaps where a user can bring their own implementations of these functions? I'll request the same behavior from the other crate's maintainer. 

Very simply, using the [a121-rs](https://github.com/Ragarnoy/a121-rs/) crate and esp-wifi together doesn't work.

**Comment by bjoernQ** [comment]
I don't see where that library implements `malloc` and `free` - they are depending on these functions to be present here: https://github.com/Ragarnoy/a121-rs/blob/1d5453267be450a30104def8ac3efe35da6fd840/src/hal.rs#L133-L136

The examples however seem to use `tinyrlibc` which define those symbols - probably you need to _not_ add this as a dependency
