### ISSUE TITLE
802.11r support?

### ISSUE THREAD

**Issue by sivakov512** [esp-rs/esp-hal#1624]
Hi! After few hours I found that my esp32c3 can't connect to wifi ap if 802.11r enabled. Looks like it's possible to enable ([doc](https://docs.espressif.com/projects/esp-idf/en/stable/esp32c3/api-guides/wifi.html#fast-bss-transition)), but please consult me how? Can't find any info about it

**Comment by bjoernQ** [comment]
Closing this for now. I don't have a setup to test / work on this. Feel free to submit a PR
