### ISSUE TITLE
Allow initialise `esp-wifi` without forcing CPU max clock

### ISSUE THREAD

**Issue by alevinval** [esp-rs/esp-hal#1685]
Hi folks, recent owner of an esp32s3 here, and recent joiner to the embedded world.

I am interested in running a BLE stack, ideally battery powered, saving as much power as possible. I realised that the checks below impede us from initialising at lower clock speeds:
https://github.com/esp-rs/esp-hal/blob/65b956d6a816a48dd8e21bb70ebf399a75fb003d/esp-wifi/src/lib.rs#L233-L247

The only apparent reason for these checks is because of the following, which only applies to `esp32s3`:
https://github.com/esp-rs/esp-hal/blob/65b956d6a816a48dd8e21bb70ebf399a75fb003d/esp-wifi/src/lib.rs#L249-L260

I am currently pointing to a local repository for `esp-hal` where I've got rid of this myself. So far it seems to be running fine, sending data over BLE completely fine, with the clock set at 80MHz. Addressing this would be a good starting point to be low power friendly.

If there is no rationale for those checks, should we remove them? And if there is a rationale, it may be good to document it.

I'd be happy to contribute myself, but I ask first because I have no idea what I'm doing.

**Comment by bjoernQ** [comment]
IIRC the minimum CPU clock to use the radios is 80MHz so we can probably lift that requirement 

Ideally we should support modem-sleep for BLE in future but I didn't get it to work when I tried last time (we have it working fine for WiFi already)

**Comment by alevinval** [comment]
I guess we can close this now.
