### ISSUE TITLE
H2: Enabling the IEEE802.15.4 peripheral causes the builtin JTAG peripheral to stop working

### ISSUE THREAD

**Issue by PortalRising** [esp-rs/esp-hal#1706]
I programmed the [ieee802154_receive_frame](https://github.com/esp-rs/esp-hal/blob/main/examples/src/bin/ieee802154_receive_frame.rs) example onto a [ESP32-H2-DEV-KIT-N4](https://www.waveshare.com/wiki/ESP32-H2-DEV-KIT-N4) by Waveshare using the builtin JTAG peripheral and the H2 becomes unresponsive and I am unable to be reprogram the board when the example is running.

# To Reproduce

Flash the [ieee802154_receive_frame](https://github.com/esp-rs/esp-hal/blob/main/examples/src/bin/ieee802154_receive_frame.rs) example onto the H2 with

    cargo esp32h2 --bin ieee802154_receive_frame 

Then attempt to reprogram the board with any example such as the [hello_world](https://github.com/esp-rs/esp-hal/blob/main/examples/src/bin/hello_world.rs) with

    cargo esp32h2 --bin hello_world

Espflash outputs this and just hangs until forcefully stopped

         Finished `release` profile [optimized + debuginfo] target(s) in 0.63s
         Running `espflash flash --monitor target/riscv32imac-unknown-none-elf/release/hello_world`
    [2024-06-23T14:26:33Z INFO ] 🚀 A new version of espflash is available: v3.1.0
    [2024-06-23T14:26:33Z INFO ] Serial port: '/dev/ttyACM0'
    [2024-06-23T14:26:33Z INFO ] Connecting...

Finding a solution for #1623 may fix this issue if merged into the esp-ieee802154 crate as well.

**Comment by bjoernQ** [comment]
> Finding a solution for https://github.com/esp-rs/esp-hal/issues/1623 may fix this issue if merged into the esp-ieee802154 crate as well.

Yes - I'm really interested in finding a solution for that. (You probably already know but to can get the board to be flashable again by manually putting it into download mode)

**Comment by MabezDev** [comment]
Closing in favour of tracking in #1623
