### ISSUE TITLE
Add documentation checks back to our CI workflow (or, create a new workflow for this)

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#1718]
Previously we were building documentation for `esp-hal` in CI for each workflow run. For \~\*\~reasons\~\*\~ these checks were removed some time back, and should be re-added.

However, I'm not sure our previous strategy was the best one. For once, we were not verifying the documentation of all packages. Additionally, I'm not sure it's necessary to perform these checks in each CI run, and this was drawing out the workflow runtime (IMO) unnecessarily.

Perhaps a nightly run is enough? Maybe another strategy would be better? Let's discuss.

**Comment by bjoernQ** [comment]
I _think_ without documenting all dependencies generating docs is much cheaper now but probably having that checked only in a nightly run is good enough. And when we create such a workflow we probably could also add some other expensive checks there (cannot think of anything right now but probably we will find something)

**Comment by jessebraham** [comment]
Yes that's a good point, thanks for mentioning that. Perhaps that is less of an issue now.

I think we will spend some time during our team meeting tomorrow to discuss CI, and can cover this topic then.
