### ISSUE TITLE
`Input` does not implement `RtcPin`

### ISSUE THREAD

**Issue by dimpolo** [esp-rs/esp-hal#1729]
I'd like to express something like:
```rust
let mut pin = Input::new(io.pins.gpio4, Pull::None);
// use pin normally here

let ext0 = Ext0WakeupSource::new(&mut pin, WakeupLevel::High);
// use pin as a deep sleep wakeup source
```

This was possible before #1542.

We could either implement `RtcPin` for the wrapper structs or add a method to the wrapper structs that recovers the underlying `Gpio` struct

**Comment by bjoernQ** [comment]
You should be able to pass `&mut` into the input pin driver and then drop the driver before using it as the wakeup pin I guess - on mobile right now so can't try it before tomorrow morning

**Comment by bjoernQ** [comment]
I think we at least need to document the general pattern (which applies to all drivers) somewhere. It's really not obvious how to do those things
