### ISSUE TITLE
Add the `links` field to the Cargo manifest of `esp-println` and potentially other packages

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#1731]
It's currently possible to accidentally include multiple versions of `esp-println` in your project, which results in compilation errors when the build script is performing the feature verification.

This should be resolvable by simply adding `links = "esp-println"` to `esp-println/Cargo.toml` under the `[package]` section.

Additionally, we should evaluate which, if any, other packages should receive this change, and update all relevant packages.

**Comment by jessebraham** [comment]
@bjoernQ I'm not sure any other packages really need it at this point, can you think of any? If not I'll add this field and close this issue.

**Comment by bjoernQ** [comment]
> @bjoernQ I'm not sure any other packages really need it at this point, can you think of any? If not I'll add this field and close this issue.

I don't think any other package needs it - thanks for taking care of this
