### ISSUE TITLE
Reduce / eliminate cache misses in interrupt handling

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#1747]
Follow up on #1162 - there are some more insights in the linked issue

Remaining tasks

- [ ] Replace `const`s this `static`'s if they're referenced in interrupt handling code
- [ ] Put jump tables in RAM
    - Linker magic to place them in RAM on a best effort basis

There is even more to put into RAM to avoid hitting flash. To really see where code accesses flash its best to look at disassembled code

We _need_ to make this opt-in since it will decrease remaining useable RAM which might be a problem for some applications.

Given we don't want to introduce more features this means need #1111 first

**Comment by MabezDev** [comment]
Now with some configuration options we can opt into placing more of these things into IRAM

**Comment by bugadani** [comment]
If we aim to reduce cache misses, we might want to optimize IRAM code to size. The attribute [exists](https://github.com/rust-lang/rust/issues/54882#issuecomment-457824508) in nightly, so if we want a config to enable nightly-specific features we can do this automagically for all IRAM code.
