### ISSUE TITLE
Remove uneccessary bitfield from I2C driver

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#1751]
Not sure why we merged this when patching the PAC would have been trivial, but our I2C driver currently contains a bitfield definition for the command registers:  
https://github.com/esp-rs/esp-hal/blob/c4ad9d37ab11a740fdd7f18d48b89f6fd59f90f4/esp-hal/src/i2c.rs#L133-L184

The PACs should be patched and this should be removed.

**Comment by playfulFence** [comment]
As soon as https://github.com/esp-rs/esp-pacs/pull/259 is resolved, I'll do the patch for the PAC
