### ISSUE TITLE
esp-ieee802154: crate can not be found on crates.io

### ISSUE THREAD

**Issue by cracksalad** [esp-rs/esp-hal#1752]
The esp-ieee802154 crate can not be found at all on crates.io or via cargo. Although I found the source code here in this repo. What is going on here? Is it just a failed automation or is it planned (e.g. because it has been moved somewhere or renamed)?

## crates.io

![grafik](https://github.com/esp-rs/esp-hal/assets/28577589/b673c4a6-4489-4172-8c14-a6ccfe4736bc)

## attempt to add using cargo

```bash
$ cargo add esp-ieee802154
    Updating crates.io index
error: the crate `esp-ieee802154` could not be found in registry index.
```

## except from README.md here in GitHub (main branch as well as v0.18.0 tag)

![grafik](https://github.com/esp-rs/esp-hal/assets/28577589/002b9256-c441-4577-8352-35da9d246166)

**Comment by jessebraham** [comment]
We have not published this package yet. There is a tracking issue already open for this: https://github.com/esp-rs/esp-hal/issues/1655
