### ISSUE TITLE
Certain PRs do not trigger the CI workflow and need to be merged manually with branch protections bypassed

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#1762]
See:

- https://github.com/esp-rs/esp-hal/pull/1745
- https://github.com/esp-rs/esp-hal/pull/1761

**Comment by bjoernQ** [comment]
I thought about having a `dummy_ci.yml` workflow which only triggers on CHANGELOG and README _but_ I think that would be very dangerous - i.e. having a failing build and then changing CHANGELOG.md would result is everything being shiny green.

So probably the only safe thing to do it to _not_ path-exclude in `ci.yml`?
