### ISSUE TITLE
Improve DMA Channel APIs

### ISSUE THREAD

**Issue by Dominaezzz** [esp-rs/esp-hal#1767]
There are currently two main issues with the channel API.
1. Naming types that use DMA is more verbose/tedious than it should be, see #1699. This applies to drivers that only use one half of the channel, i.e. LCD_CAM. (At the moment PARL_IO take the whole channel)
2. On hardware that uses GDMA (and not PDMA) you have to configure both channels at the same time. The APIs should let you separately configure the RX half and TX half of the peripheral. Also see [this comment](https://github.com/esp-rs/esp-hal/pull/1480#discussion_r1574192380).

**Comment by liebman** [comment]
This should include adding the Async/Blocking notation on the TX and RX portions - currently at least the LCD_CAM I8080 driver takes this in its constructor but there is no way for the compiler to know if its async or blocking.
