### ISSUE TITLE
Document dma Channel type alias

### ISSUE THREAD

**Issue by VersBinarii** [esp-rs/esp-hal#1773]
Documentation regarding the Channel types could be a little more exlicit that the internal Channels types are in fact exposed as type alias i.e. Channel<0> is reexported as Channel0 

Context: https://matrix.to/#/!LdaNPfUfvefOLewEIM:matrix.org/$kNyGi9KVlrh1ffysI27aqc7AJUVqCdH9RAu8ADA4VCY?via=matrix.org

**Comment by Dominaezzz** [comment]
The type aliases are gone now, or at least they're no longer useful for the circumstances that warranted this issue.

**Comment by bjoernQ** [comment]
Maybe we could change of the examples in a way that a channel is passed or stored somewhere. It's now a lot easier but maybe still worth to have it 🤷‍♂️
