### ISSUE TITLE
Running `embassy_hello_world` example stand-alone

### ISSUE THREAD

**Issue by lure23** [esp-rs/esp-hal#1781]
I noticed that currently (10-Jul-24) the Embassy examples cannot be reproduced outside of the `cargo xtask` setup. This is down to the publication of the latest code to `crates.io`.

This boils down to one of two routes:

- If targeting a (single) known chip, see [here](https://github.com/esp-rs/esp-template/issues/110)
- If wanting to target 2 or more chips, see [ESP32-Embassy sample](https://github.com/lure23/ESP32-Embassy-sample) - a small repo I made to document the current state and steps I took.

The aim is to:

- be able to work on `cargo` only (using `xtask` internally for `esp-hal` is fine of course!)
- be able to pull reasonably working 😉 versions from `crates.io` - no file paths needed for dependencies

**I am confident this will happen in its due course.** In the interim, decided to leave an issue so that:

- others will easily see "what's up"
- there's a place to follow this *from the point of outside usage* - not merely from within `esp-hal`

**Comment by jessebraham** [comment]
Thank you for opening this issue. We are aware that this currently quite difficult, sorry that you have been having problems. We're planning on publishing a new round of packages next week, and following that our next release cycle will be focused on improving usability. I will be sure to mention this issue during our team's planning meeting next week.

In the meantime, while this is not a true solution, I have made a template for using `esp-hal` with `embassy`, which you can find here:  
https://github.com/jessebraham/esp-hal-template

It's still quite basic, but at least should generate the boilerplate needed to build an Embassy application without relying on our `xtask` package. If you have any problems or additional requests, please feel free to open one or more issues on that repository. I threw this together pretty quick yesterday, so there may be some minor issues; I plan to expand on it a bit this weekend.

**Comment by lure23** [comment]
No worries! The repo you linked to was helpful in seeing which dependencies are really needed. 

Glad to be on this ride!  Nice to know momentum is there.

**Comment by lure23** [comment]
Looks fine now, with `esp-hal` 0.19.0 et.al.
