### ISSUE TITLE
release `esp-backtrace` 

### ISSUE THREAD

**Issue by felixwrt** [esp-rs/esp-hal#1808]
#1800 bumped the version to 0.12.2, but it seems like it's not released yet. I'm trying to upgrade a project using `esp-hal` to 0.19.0 and I'm currently stuck because `esp-hal 0.19` depends on `esp-println 0.10.0` while the latest released `esp-backtrace` still depends on `esp-println 0.9.1`

**Comment by MabezDev** [comment]
esp-backtrace 0.13 will be released shortly once https://github.com/esp-rs/esp-hal/pull/1804 is merged.

**Comment by MabezDev** [comment]
0.13 has been released, sorry about that!

**Comment by felixwrt** [comment]
No problem, thanks for the quick fix
