### ISSUE TITLE
`usb_serial_jtag` example freezes when pressing a key

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#1811]
While `embassy_usb_serial_jtag` works - `usb_serial_jtag` doesn't work for me. Tested on ESP32-S3, ESP32-C3, ESP32-C6 ... all the same.

**Comment by JurajSadel** [comment]
I tried to run the `usb_serial_jtag` and `embassy_usb_serial_jtag` examples and both are working for me. I will try to run them on Windows later today as well

**Comment by bjoernQ** [comment]
On Windows using espflash (3.1.0) this is 100% reproducible. However using putty it doesn't freeze for me.

Still the embassy example works so there is _something_ strange here

**Comment by JurajSadel** [comment]
I've tried to run it on Windows, but it doesn't recognize any USB-SERIAL-JTAG port ... I followed steps from IDF and it still doesn't work.

**Comment by bjoernQ** [comment]
This is most probably more of a problem in `espflash` than with HAL code. While the problem is seen when flashing and monitoring the problem isn't present when just flashing and the running `espflash monitor` separately

**Comment by bjoernQ** [comment]
Recreating the serialport instance before monitoring might help - in any case this is definitely not a HAL issue but an espflash issue
