### ISSUE TITLE
Add CFI annotations to our assembly

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#1815]
CFI helps rustc generate better debug symbols.

**Comment by bugadani** [comment]
Can you please explain what triggered closing this issue?

**Comment by MabezDev** [comment]
Mostly because it's been open for a few years and I don't think we'll ever get around to it, nor do I feel it's actually that important to do in the grand scheme of things. I'm not aware of any debug-ability issues with the way things currently are, but I might be misinformed :D
