### ISSUE TITLE
ADC for ESP32-S3

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#182]
Currently we are missing the ADC implementation for ESP32-S3 because the SVD (and the PAC) doesn't contain it, yet.

Implement it when we have it and in a second step de-duplicate the ADC code (it's currently three similar copies of the same code)

**Comment by jessebraham** [comment]
The `SENS` peripheral has been added for the ESP32-S3 in #215, so once that's merged we can move forward with this. I think @JurajSadel was interested in tackling it.
