### ISSUE TITLE
ESP32 PSRAM duplicate branch

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#1825]
https://github.com/esp-rs/esp-hal/blob/2c8bb07be231018b2b18cad1063a4fab7e009b99/esp-hal/src/soc/esp32/psram.rs#L1142-L1146

This seems to be a bug, regardless of the condition we set the cache value the same.

cc: @bjoernQ

**Comment by bjoernQ** [comment]
I think it's just code converted from esp-idf - original code is here: https://github.com/espressif/esp-idf/blob/af25eb447e3330c21e3b38e91db16332056882b2/components/esp_psram/esp32/esp_psram_impl_quad.c#L744-L748

But I agree that last if condition doesn't make sense if the else-branch does the same
