### ISSUE TITLE
Expose interrupt state of Pin when wrapped in Input<>

### ISSUE THREAD

**Issue by ScreamsInJank** [esp-rs/esp-hal#1829]
Currently if you have an interrupt handler registered with the handler macro and multiple gpio pins it is impossible to discern which pin triggered the interrupt.

Recommendation:
Add a method to the implementation of `Input<'d, P>` which exposes `Pin::is_interrupt_set(&self, _: private::Internal) -> bool`

I'm happy to implement it and make the PR if need be.

**Comment by bjoernQ** [comment]
With #1839 merged we can close this
