### ISSUE TITLE
There is currently no way to configure WDT to do anything but a system reset

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#1831]
While we can set an interrupt handler, we currently have no way for the user to configure the WDT to cause anything but a system reset.

**Comment by playfulFence** [comment]
From the current state of <link here>

Even though I'm setting everything correctly (I'm also checking if wdt_stgX registers are in correct value), WDT constantly only resets the whole system, no matter which value is in those registers, it never fires an interrupt or if "No Action" mode is set - it still resets the whole system. 

I decided to check if that works in IDF implementation and got this result:

code (modified `test_reset_reason` unit test) : 

static void do_rtc_wdt(void)
{
    setup_values();
    // Enable RTC watchdog for 0.1 second
    wdt_hal_context_t rtc_wdt_ctx;
    wdt_hal_init(&rtc_wdt_ctx, WDT_RWDT, 0, false);
    uint32_t stage_timeout_ticks = rtc_clk_slow_freq_get_hz() / 10;
    wdt_hal_write_protect_disable(&rtc_wdt_ctx);
    wdt_hal_config_stage(&rtc_wdt_ctx, WDT_STAGE0, stage_timeout_ticks, WDT_STAGE_ACTION_OFF);
    wdt_hal_config_stage(&rtc_wdt_ctx, WDT_STAGE1, stage_timeout_ticks, WDT_STAGE_ACTION_OFF);
    wdt_hal_config_stage(&rtc_wdt_ctx, WDT_STAGE2, stage_timeout_ticks, WDT_STAGE_ACTION_OFF);
    wdt_hal_config_stage(&rtc_wdt_ctx, WDT_STAGE3, stage_timeout_ticks, WDT_STAGE_ACTION_OFF);

    wdt_hal_set_flashboot_en(&rtc_wdt_ctx, true);
    wdt_hal_write_protect_enable(&rtc_wdt_ctx);
    while (1);
}
Output: 
<img width="940" alt="image" src="https://github.com/user-attachments/assets/0721dec4-2513-4ac3-90cf-09d0d5ad2a53">

so as you can see even though `stage` registers are set to `Off` value, it still resets the whole system
