### ISSUE TITLE
Async SPI broken for ESP32

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#1857]
Since 4ef91c5941883a5dc589209eb91fe25641570686 Async-SPI is broken for ESP32

Steps to reproduce:
- connect GPIO 2 and 4
- run `cargo xtask run-example examples esp32 embassy_spi`

Expected:
It works as before

Actual:
`transfer` never returns

**Comment by bjoernQ** [comment]
(Still works for ESP32-S2)

**Comment by Dominaezzz** [comment]
I reckon this is due to the interrupts being cleared after the DMA transfer starts, I'll have time to investigate this evening and I'll add a hil test for async spi

**Comment by plaes** [comment]
Another testcase which is broken even with the DMA patch:
```rust
    let mut write_buf = &[0xaa];
    //let mut payload = &[0xd1, 0xd2, 0xd3, 0xd4];
    // Works with 1..4 bytes
    // Hangs when payload is > 4 bytes??
    let mut payload = &[0xd1, 0xd2, 0xd3, 0xd5, 0xd5];

    defmt::info!("TX... ");
    let mut ops = [Operation::Write(write_buf), Operation::Write(payload)];
    let _ = spi_dev.transaction(&mut ops).await;
    defmt::info!("...done");
```

**Comment by Dominaezzz** [comment]
Ah, unfortunately the HIL tests don't run on the ESP32... oh well, we'll have to settle for the example then.
