### ISSUE TITLE
Provide some way to *not* bind an interrupt handler in `Io::new`

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#1858]
There are cases where users may want to use the GPIO interrupt in ways other than what is currently supported, since we are setting an interrupt handler by default:  
https://github.com/esp-rs/esp-hal/blob/main/esp-hal/src/gpio/mod.rs#L1192-L1216

It would be nice to have some way to indicate that this handler should not be set.

cc @bjoernQ @MabezDev

**Comment by bjoernQ** [comment]
Easiest would be to have another constructor for this very special case - with a big warning in the docs regarding async etc. - I guess this corner case isn't worth to add type-state

**Comment by jessebraham** [comment]
I agree, this is probably the simplest path forward. Just wanted to run it past you first as you wrote most of this code in the first place 😁 Thanks for the input!
