### ISSUE TITLE
Can't produce more than 16MHz from the LEDC driver on the ESP32-C6

### ISSUE THREAD

**Issue by Dominaezzz** [esp-rs/esp-hal#1867]
Running the example https://github.com/esp-rs/esp-hal/blob/main/examples/src/bin/ledc.rs . If I chose a frequency higher that 16MHz no PWM output is produced.
For my use case I need to produce 20MHz - 24MHz .

**Comment by MabezDev** [comment]
IIRC this is not a hardware issue, and now works in idf - removing the blocked label.
