### ISSUE TITLE
Expose RAW 802.11 transmit API and promiscuous mode on `esp-wifi`

### ISSUE THREAD

**Issue by ProfFan** [esp-rs/esp-hal#1879]
The `esp-wifi` crate currently does not have `esp_wifi_80211_tx` and promiscuous mode available. This makes implement custom protocols (for example mesh networking) very difficult, as the ESP-NOW protocol is limited to only 250bytes of packets, which wastes a lot of bandwidth due to frame overheads.

**Comment by bjoernQ** [comment]
relates to #1603

**Comment by MabezDev** [comment]
Closed via https://github.com/esp-rs/esp-hal/pull/1935
