### ISSUE TITLE
Use SPI Bus for multiple Devices 

### ISSUE THREAD

**Issue by agmes4** [esp-rs/esp-hal#1887]
I wanna use the Spi Bus for multiple Spi Devices Problem here is that the config for one device is a bit different. 
(It is taking data on raising Edge the other on falling.)

So is there any way to change config on runtime of a SpiDeviceDriver or to create two different one so I can pass one to each devices?

**Comment by Dominaezzz** [comment]
`SpiDeviceDriver`? Did you mean to open this in https://github.com/esp-rs/esp-idf-hal ?

**Comment by Dominaezzz** [comment]
You can close this now 🙂
