### ISSUE TITLE
Add .uninit section for defmt when not using `direct-boot`

### ISSUE THREAD

**Issue by TheButlah** [esp-rs/esp-hal#191]
#179 adds support for defmt when using `direct-boot` feature. Could a similar linker script be added for when not using `direct-boot`?

Worth pinging @9names I suppose :)

**Comment by TheButlah** [comment]
It would be good to get this for the 2nd stage bootloader version of esp-hal, because esp-wifi currently only supports using the bootloader.

When the original PR was made, @9names suggested that it probably would work on the bootloader feature too, but they hadn't tried it yet. Perhaps someone could check if it works? It might be low hanging fruit.

**Comment by 9names** [comment]
I forgot to tag this issue in PR #246
