### ISSUE TITLE
Make AnyPin accessible from `::gpio::AnyPin`?

### ISSUE THREAD

**Issue by plaes** [esp-rs/esp-hal#1917]
Currently import path for `AnyPin` for esp-hal is `::gpio::any_pin::AnyPin`. Both embassy-nrf and embassy-stm32 have AnyPin under `::gpio::AnyPin`.
Would it make sense to switch to `::gpio::AnyPin` for esp-hal as well?

**Comment by bjoernQ** [comment]
Not saying we shouldn't but re-exporting the types doesn't look too nice in the docs:

![image](https://github.com/user-attachments/assets/710902c8-0a68-4a44-8794-7496911a09a9)

If we think this improves the user experience we might want to move the code from the module into the super-module - originally, I wanted to have it separated because `gpio.rs` is already quite large

However no strong opinion on this - just something to consider

**Comment by plaes** [comment]
Hmm.. need to check how `#[doc(inline)]` affects this.

**Comment by plaes** [comment]
> Not saying we shouldn't but re-exporting the types doesn't look too nice in the docs:
> 
> ![image](https://private-user-images.githubusercontent.com/5682593/356971278-710902c8-0a68-4a44-8794-7496911a09a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzI1NDgsIm5iZiI6MTcyMzUzMjI0OCwicGF0aCI6Ii81NjgyNTkzLzM1Njk3MTI3OC03MTA5MDJjOC0wYTY4LTRhNDQtODc5NC03NDk2OTExYTA5YTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMDY1NzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWYwNjQ3NWUwNDE1ZjA2NTI3YjNlYTNmZWM2YzdlZjViN2MwNDI1ODUzYjA4MzI3NWIyOTZiZjE4YjZkZWI0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1dCEVLqUMki-6Q7afuO3kBnRT6XbNx3GgdAtkZUaHg4)
> 
> If we think this improves the user experience we might want to move the code from the module into the super-module - originally, I wanted to have it separated because `gpio.rs` is already quite large
> 
> However no strong opinion on this - just something to consider

I seem to managed to fix it by hiding the documentation for `any_pin` submodule via `#doc(hidden)`. I still kept it public to not break existing applications, but it doesn't show up in documentation anymore.
Unfortunately there doesn't seem to be a way to mark a certain import path as deprecated.
