### ISSUE TITLE
Implement embassy_embedded_hal::SetConfig

### ISSUE THREAD

**Issue by phemmer** [esp-rs/esp-hal#1919]
This is a feature request to implement [embassy_embedded_hal::SetConfig](https://docs.embassy.dev/embassy-embedded-hal/git/default/trait.SetConfig.html) on anything which currently implements SpiBus (which would be Spi and SpiDma).

This would be useful with SpiDeviceWithConfig ([blocking](https://docs.embassy.dev/embassy-embedded-hal/git/default/shared_bus/blocking/spi/struct.SpiDeviceWithConfig.html) and [async](https://docs.embassy.dev/embassy-embedded-hal/git/default/shared_bus/asynch/spi/struct.SpiDeviceWithConfig.html)) for running multiple SPI devices with different clock speed capabilities on the same bus.

Yes, the user (me) could put a wrapper around Spi/SpiDma to implement SetConfig, and that might be what I do as a short term solution. But Just thought it would be good to have a native implementation.

**Comment by Dominaezzz** [comment]
Related https://github.com/esp-rs/esp-hal/issues/1666 and https://github.com/esp-rs/esp-hal/issues/1826
