### ISSUE TITLE
Remove all remaining `#![allow(missing_docs)]` attributes and finish documenting all public types

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#1938]
The following modules contain this attribute, and require further documentation:

- [x] `ecc`
- [x] `etm`
- [x] `hmac`
- [x] `i2c`
- [x] `i2s`
- [x] `lcd_cam`
- [x] `ledc`
- [x] `otg_fs`
- [x] `pcnt`
- [x] `rsa`
- [x] `rtc_cntl`
- [x] `sha`
- [x] `soc`
- [x] `spi`
- [x] `system`
- [x] `twai`
- [x] `uart`

**Comment by playfulFence** [comment]
I'm done with most of the tasks that have been assigned to me so far, so I'm gonna take a little "break" and take some care of this one for now
