### ISSUE TITLE
Decide on ordering of Tx/Rx pairs in APIs

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#1986]
We should decide on an order, and add it to the API guidelines, then check that all APIs that return or consume a tx/rx pair use that order.

**Comment by bugadani** [comment]
Well, obviously `tx, rx` is the only right way to do it :)

Btw we might want to think about this a bit more generally, there are some inconsistent things in the HAL, like:

![image](https://github.com/user-attachments/assets/94bf0cec-7d5c-42e7-a2b9-554650b00942)
(timer, clocks, vs clocks, timer)

**Comment by AnthonyGrondin** [comment]
`embassy-net` and `smoltcp` both seem to be using `rx, tx`.

**Comment by MabezDev** [comment]
In our internal meeting we decided to try and be consistent with the ecosystem, we will use `rx, tx`.

**Comment by SergioGasquez** [comment]
> Well, obviously `tx, rx` is the only right way to do it :)
> 
> Btw we might want to think about this a bit more generally, there are some inconsistent things in the HAL, like:
> 
> ![image](https://private-user-images.githubusercontent.com/977627/360450770-94bf0cec-7d5c-42e7-a2b9-554650b00942.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzM2NTAsIm5iZiI6MTcyNTUzMzM1MCwicGF0aCI6Ii85Nzc2MjcvMzYwNDUwNzcwLTk0YmYwY2VjLTdkNWMtNDJlNy1hMmI5LTU1NDY1MGIwMDk0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxMDQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTg0OWViNzAzZWZiYTYwNDUwNGQwNWQ3ZjBkNmE3YzRjZjU1OTg4YjVjNjFlMWYxZTkzMDQxYTQxYzg5NTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z0Wx9N0ouMdsUnRAY-6sD4sBeN1OLuBGReDcEEMU26s) (timer, clocks, vs clocks, timer)

I guess after https://github.com/esp-rs/esp-hal/pull/1999 clocks/timer is no longer an issue
