### ISSUE TITLE
esp_hal implementeation of embedded_hal I2C transaction adjacent read operations seem to not follow spec

### ISSUE THREAD

**Issue by yanshay** [esp-rs/esp-hal#1998]
I'm working with `PN532` using `I2C`. I need to read data where the first byte is `0x01`, followed by a set of bytes. The crate I'm using wants to skip the `0x01` so it's using:

```
        let res = self.i2c.transaction(
            I2C_ADDRESS,
            &mut [Operation::Read(&mut first_byte), Operation::Read(buf)],
        );
```
What I get using this is  `[1] then [1, 0, 0, 255, 0, 255]`, so the 1 is repeating. If I make multiple short reads the `0x01` arrives in every read (even 2 or 3 bytes).

If I issue a single large read I get only the `[1, 0, 0, 255, 0, 255]`, so the '1' doesn't appear twice. 
From that I conclude that either the read operation is sent twice on the i2c (the device notices that and responds with the full transaction every time until the complete data is read), or that there is some buffering inside `esp_hal`.

`embedded-hal` states that 'Data from adjacent operations of the same type are sent after each other without an SP or SR.', which I understand means that the device should not see two read operations but rather a single one. My understanding is that the crate I'm using works that way on other devices (not esp32), so it's not a PN532 behavior.

This is the complete info regarding `embedded_hal` reqirements from their source:

```
    /// Execute the provided operations on the I2C bus.
    ///
    /// Transaction contract:
    /// - Before executing the first operation an ST is sent automatically. This is followed by SAD+R/W as appropriate.
    /// - Data from adjacent operations of the same type are sent after each other without an SP or SR.    <----------
    /// - Between adjacent operations of a different type an SR and SAD+R/W is sent.
    /// - After executing the last operation an SP is sent automatically.
    /// - If the last operation is a `Read` the master does not send an acknowledge for the last byte.
    ///
    /// - `ST` = start condition
    /// - `SAD+R/W` = slave address followed by bit 1 to indicate reading or 0 to indicate writing
    /// - `SR` = repeated start condition
    /// - `SP` = stop condition
    fn transaction(
        &mut self,
        address: A,
        operations: &mut [Operation<'_>],
    ) -> Result<(), Self::Error>;
```

**Comment by liebman** [comment]
I see whats going on and should have a PR in a few days.

**Comment by liebman** [comment]
@yanshay can you give PR #2028 a try?
