### ISSUE TITLE
API consistency for GPIO types

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#2006]
We should ensure that all our GPIO types have a consistent API across them all.

This may include making the Output/Input traits public again.

Related to #1995

**Comment by bugadani** [comment]
> This may include making the Output/Input traits public again.

Which traits are you referring to? `InputPin` and `OutputPin` are still public.

**Comment by Dominaezzz** [comment]
The APIs on them aren't public in a meaningful way. They have the `crate::Internal` param to prevent users from using them directly.

**Comment by bugadani** [comment]
Right. Well, things will change.
