### ISSUE TITLE
SHA is waaaaay too easy to misuse

### ISSUE THREAD

**Issue by bugadani** [esp-rs/esp-hal#2041]
- Creating multiple peripheral drivers is trivial and at each time it resets the peripheral (https://github.com/esp-rs/esp-hal/blob/v0.20.0/esp-hal/src/sha.rs#L427-L444). This makes the driver a gigantic footgun when used in multiple contexts
 - We're accessing the peripheral in `process_buffer` in a racy way

**Comment by Dominaezzz** [comment]
Depending on how quickly you want this fixed, I'm interested in taking care of this.

I can keep to the `0.21.0` deadline.
