### ISSUE TITLE
esp-hal 0.20.0 appears to be broken

### ISSUE THREAD

**Issue by pebender** [esp-rs/esp-hal#2043]
The code contains references to the file  '../esp-hal/doc-helper/before'. For example,

https://github.com/esp-rs/esp-hal/blob/5917275108f767e80b476bb60e792f80a2b64e02/esp-hal/src/lib.rs#L630

This does not work with the release as cargo appends the version number to the downloaded crate so as to avoid conflicts. As a result, the file is in '../esp-hal-0.20.0/doc-helper/before' not '../esp-hal/doc-helper/before'.

**Comment by AnthonyGrondin** [comment]
https://github.com/esp-rs/esp-hal/pull/2040 fixes this issue

**Comment by MabezDev** [comment]
https://github.com/esp-rs/esp-hal/releases/tag/v0.20.1 is now released on crates.io, sorry for the inconvenience!
