### ISSUE TITLE
RGB Interface Support for esp32-s3

### ISSUE THREAD

**Issue by jacobzlogar** [esp-rs/esp-hal#2081]
I would like to get an idea of what's needed to implement a RGB interface for the LCD_CAM module, i was told by @Dominaezzz that the DMA api's aren't currently powerful enough to support RGB mode. For context i'm attempting to use a [qualia esp32s3](https://www.adafruit.com/product/5800) board from adafruit that uses a RGB TTL connector

**Comment by Dominaezzz** [comment]
Long story short, all the options available in https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/api-reference/peripherals/lcd/rgb_lcd.html should be supported by the hal. Either by having the implementation here or providing APIs for users to DIY it. (I much prefer the latter).

**Comment by Dominaezzz** [comment]
We also need one of the maintainers to have a devkit that can run an example with it, like [ESP32-S3-LCD-EV-Board](https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32s3/esp32-s3-lcd-ev-board/index.html).

**Comment by Dominaezzz** [comment]
Now that #2242 (with the DMA buffer view feature) has landed, I can submit a PR for this.
All the (non PSRAM related) features needed for a decent no_std version of esp_lcd can now be implemented outside of esp-hal.
The XIP from PSRAM feature is still an important piece of the puzzle but that doesn't have to block the initial driver.
