### ISSUE TITLE
Question about sync devices on esp-now

### ISSUE THREAD

**Issue by PabloSalinas27** [esp-rs/esp-hal#2088]
Hi! I'm looking to sync several (less than the max peer count, 4 or 5) esp32 devices down to ~100 us. I read that I could make a ntp/ptp bespoke implementation on top of esp-now, but another route, probably easier and more accurate (down to 10 us or less) is using the tsf of the wifi signal. I'm not sure how would I do that with esp-wifi. It is ok for me to use esp-wifi-sys, but I'm not sure how would I proceed.
Thanks for the help!

**Comment by MabezDev** [comment]
If you use esp-wifi-sys you'll have to roll your own everything to interact with the binaries - this is out of the scope of what we can support. I suggest using esp-now.
