### ISSUE TITLE
probe-rs freezes the current running program

### ISSUE THREAD

**Issue by Szybet** [esp-rs/esp-hal#2092]
As I don't know who to bother and who's fault it is, I post it here too. Everything explained here: https://github.com/probe-rs/probe-rs/issues/2799

Thanks :)

**Comment by bugadani** [comment]
Please stop spamming the same issue everywhere. It's most likely probe-rs related. Just run `probe-rs run` for now, it works fine.

**Comment by Szybet** [comment]
I'm not spamming, I just posted it in 2 places :(

Ok, I'm gonna continue the conversation there.

Well no, when trying to implement an OTA system, attach is the only way to go.
