### ISSUE TITLE
Add strip support to esp-lp-hal

### ISSUE THREAD

**Issue by Szybet** [esp-rs/esp-hal#2121]
When trying to:
```
[profile.release]
strip = true 
```
The program that tries to load the binary complains that it's not a ULP program. That's because strip removes the `__ULP_MAGIC_` symbol. I was not able to keep it via linker script magic. The work around I was able to do is removing argument support:

https://github.com/esp-rs/esp-hal/compare/main...Szybet:esp-hal:esp-lp-hal-strip

I don't know if it's possible to remain the symbol with strip, but it's worth it. For a simple blinky program it saves 1-2 Kb. Also everything seems to work fine, I just need to:
```
let pin: Output<3> = Output {};
```
I don't know the perfect solution for this, maybe a feature but I have no idea if they would work with those macros.

Any thoughts?

**Comment by MabezDev** [comment]
> For a simple blinky program it saves 1-2 Kb

How did you measure this?

iirc `strip` does nothing on embedded programs. `strip` is only useful for reducing the size of an elf by `strip`ping the debug symbols etc. For an embedded system, only the loadable sections of an ELF are actually flashed to the board.

**Comment by MabezDev** [comment]
> `stat -c %s`

On which file are you running this command, on the ELF, i.e `esp-lp-hal/target/riscv32imc-unknown-none-elf/release/examples/blinky` or something else?

> How do I get a binary of the lp program that could be loaded from esp-idf? (Because I think it would be an awesome way to start using rust in esp-idf projects who want to use the lp core)

I'm not sure I follow this bit, but maybe @bjoernQ knows what you mean?

**Comment by bjoernQ** [comment]
If you want to see the size of code/data in memory you could use something like `riscv32-esp-elf-size esp-lp-hal\target\riscv32imc-unknown-none-elf\release\examples\blinky`

This outputs e.g.
```
   text    data     bss     dec     hex filename
   1392       4       0    1396     574 esp-lp-hal\target\riscv32imc-unknown-none-elf\release\examples\blinky
```

i.e. 1396 bytes

ESP-IDF uses its own mechanism to build and include LP-core code - see https://github.com/espressif/esp-idf/blob/59e18382702b6986be3d3f55e9ac7763c1397cf7/components/ulp/cmake/IDFULPProject.cmake#L194-L198 - TL;DR it's using `objcpy`

**Comment by Szybet** [comment]
I'm running it on `target/riscv32imac-unknown-none-elf/release/yatchy-lp-program` so it's good, and this binary gets smaller by applying strip

I got confused at this point, how do I get the bare memory which will be putted to rtc memory and executed? I think it's the file I wrote the path above?

**Comment by bjoernQ** [comment]
> I got confused at this point, how do I get the bare memory which will be putted to rtc memory and executed? I think it's the file I wrote the path above?

No - that's the elf - running `size` on it will show text and data size (i.e. what gets into LP/RTC memory)

**Comment by Szybet** [comment]
Oh... Yea, now strip doesn't do anything... Nevermind

`cargo objcopy --release -- -O binary out/yatchy-lp-program-new.bin` and I have the pure binary

Thanks for clearing out my confusion :smile:
