### ISSUE TITLE
`i2s` examples broken with #2074

### ISSUE THREAD

**Issue by JurajSadel** [esp-rs/esp-hal#2129]
Examples crash with:
```rust
====================== PANIC ======================
panicked at /Users/jurajsadel/esp-rs/esp-hal/esp-hal/src/dma/mod.rs:769:33:
called `Option::unwrap()` on a `None` value
```

Interestingly enough, calling the arguments in the original order makes it working"i.e:
`let (_, tx_descriptors, rx_buffer, rx_descriptors) = dma_buffers!(0, 4092 * 4);` works

**Comment by bjoernQ** [comment]
> Interestingly enough, calling the arguments in the original order makes it working"i.e:
let (_, tx_descriptors, rx_buffer, rx_descriptors) = dma_buffers!(0, 4092 * 4); works

Thanks to that hint I can confirm that b5f0246 broke it - hopefully that makes the problem easier to spot
