### ISSUE TITLE
`I2C` is not working for the ESP32-C2 in release builds

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#213]
This was a known issue when support for this device was merged, but will need to be resolved before we're able to publish a release of `esp32c2-hal`.

**Comment by bjoernQ** [comment]
Out driver implementation assumes a FIFO size of 32 bytes but on ESP32-C2 it is 16. Just doing that however still doesn't get the SSD1306 example to work

To make that happen we need to change the driver from NON-FIFO to FIFO-MODE of operation
