### ISSUE TITLE
ESP32-C6: spi_loopback_dma example broken (but apparently not just the example)

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#2151]
## Bug description

Running the example prints this on ESP32-C6

```
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] .. [73, 74, 75, 76, 77, 78, 79, 7a, 7b, 0]
[0, 1, 0, 0, 0, 0, 0, 1, 1, 1] .. [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 2, 0, 0, 0, 0, 0, 1, 1, 1] .. [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
```

So, it's failing after the first iteration

The tests don't fail because they only test one transfer

Seems the offending commit is b5f0246129187dfc9342f4c170e281028138f7e1

## To Reproduce

Run the example

## Expected behavior

Example works as before

## Environment

Chip type:         esp32c6 (revision v0.0)
Crystal frequency: 40 MHz
Flash size:        4MB
Features:          WiFi 6, BT 5
MAC address:       60:55:f9:f6:01:78

esp-hal commit 562c891ef9bfbb085755ba3029b6efabd9b72935

**Comment by Dominaezzz** [comment]
It's probably the DMA timing issue now that TX is done after RX. See https://github.com/esp-rs/esp-hal/pull/1856#issuecomment-2266175855
