### ISSUE TITLE
How about adding a typical result of `wifi_bench` in the documentation

### ISSUE THREAD

**Issue by wuwbobo2021** [esp-rs/esp-hal#2162]
Thanks to <https://github.com/esp-rs/esp-hal/pull/2079>, I was able to run this example without any modification on my hardware (ESP32S2FH4). The download speed is about 150KB/s, upload speed is about 250KB/s. Strangely, the IDF `iperf` example running on the same hardware is more than 10 times faster. I’d like to see a typical result of `wifi_bench`.

**Comment by bjoernQ** [comment]
esp-wifi's defaults are rather conservative (i.e. low resource usage)

Inspiration of what settings are worth to change: https://github.com/esp-rs/esp-wifi-sys/pull/430
