### ISSUE TITLE
esp-wifi: RFC Remove `embedded-svc`

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#2166]
We optionally implement the wifi trait (and accompanying types) from `embedded-svc` - is that useful to someone or is it just unnecessary burden?

Is anyone actually using it (for non-esoteric reasons)?

**Comment by MabezDev** [comment]
From our meeting, we decided to remove support for now. We can always re-add it, but right now we don't see the value as not many crates (any?) build on top of these traits.
