### ISSUE TITLE
GDMA vs DMA interrupt bit discrepancies

### ISSUE THREAD

**Issue by Dominaezzz** [esp-rs/esp-hal#2193]
Whilst drafting a PR to enumset-ify the DMA interrupts I noticed some discrepancies in the interrupts of the `RegisterAccess` implementations.

### `is_in_done()` different between GDMA and PDMA
[GDMA](https://github.com/esp-rs/esp-hal/blob/v0.20.1/esp-hal/src/dma/gdma.rs#L300) says it's `IN_SUC_EOF`.
[I2S PDMA](https://github.com/esp-rs/esp-hal/blob/v0.20.1/esp-hal/src/dma/pdma.rs#L628) and [SPI PDMA](https://github.com/esp-rs/esp-hal/blob/v0.20.1/esp-hal/src/dma/pdma.rs#L231) say it's `IN_DONE`. (This is probably the wrong one)

### `is_out_done()` different between GDMA and PDMA
[SPI PDMA](https://github.com/esp-rs/esp-hal/blob/v0.20.1/esp-hal/src/dma/pdma.rs#L150) and [GDMA](https://github.com/esp-rs/esp-hal/blob/v0.20.1/esp-hal/src/dma/gdma.rs#L194) says it's `OUT_TOTAL_EOF`.
[I2S PDMA](https://github.com/esp-rs/esp-hal/blob/v0.20.1/esp-hal/src/dma/pdma.rs#L547) says it's `OUT_EOF`. (This is probably the wrong one)

### out_eof inconsistency (in both GDMA and PDMA)
`listen_out_eof()`/`unlisten_out_eof()`/`is_listening_out_eof` says it's `OUT_TOTAL_EOF`.
`is_out_eof_interrupt_set()`/`reset_out_eof_interrupt()` says it's `OUT_EOF`.
Hard to say which is wrong here at a glance.

**Comment by bjoernQ** [comment]
I think it was better aligned in the beginning and diverged at some point

Would be good to have things more aligned but I also remember that in some cases things named the same were apparently not behaving the same way for ESP32/ESP32-S2 vs other chips - but I agree that in those cases the function names should at least not suggest what is used under the hood but what it is expected to do / check
