### ISSUE TITLE
esp-config: validation of input

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#2206]
## Motivations

We should offer some way to validate the user provided options make sense, this may include:

* [ ] Ensuring provided integers are between upper and lower ranges (what about multiple ranges?)
* [ ] Ensuring that _some_ strings are from a select list of viable options, i.e users could only choose between `["uart", "usb", "usb-serial-jtag"]`, everything else would be invalid.

**Comment by jessebraham** [comment]
I will take this issue, but I would like to come up with a concrete task list in case there is any further validation required which is not already listed above. @MabezDev @tom-borcin let's please discuss this in our meeting tomorrow.
