### ISSUE TITLE
TWAI was panicked for ESP32-S3

### ISSUE THREAD

**Issue by TuEmb** [esp-rs/esp-hal#2252]
## Bug description
![image](https://github.com/user-attachments/assets/032a1cab-f72f-4f9f-9fe1-ccb4a7e4965a)
**Twai driver** crashes with invalid DLC. I'm using **ESP32-S3** to receive CAN packets using `embassy-twai` example, and sometimes I encounter this error.

From my debugging, this issue occurs when TWAI receives a frame with DLC > 8 (which is unexpected because my system uses **Basic CAN**, where no frame should have DLC > 8). The issue is difficult to reproduce since it randomly occurs after 30 minutes or more. I will continue debugging to identify the root cause.

Do you guys have any ideas with that case ?

## To Reproduce

T.B.D

## Expected behavior
We need to handle the case where **DLC is greater than 8** because it's possible. I checked esp-idf, and they handle the DLC by adding a bit to indicate **DLC_NON_COMP** in their TWAI frame struct. Therefore, I suggest adding the following:

```rust
pub enum EspTwaiError {
    /// TWAI peripheral has entered a bus-off state.
    BusOff,
    /// Data length code is larger than 8. This will break compliance with ISO 11898-1.
    DlcNoneComp,
    /// Encapsulates errors defined by the embedded-hal crate.
    EmbeddedHAL(ErrorKind),
}
```

## Environment

- Target device: ESP32-S3 
- Crate name and version: esp-hal (0.20.1)

**Comment by bugadani** [comment]
Hello, thank you for your report. Please include which esp-hal version you're using.

**Comment by TuEmb** [comment]
Yes, current latest main branch also occurs. I also tested with `esp-hal 0.20.1`. I just added version `0.20.1` on description
