### ISSUE TITLE
Peripheral signal API does not force signals to be routed through the GPIO matrix

### ISSUE THREAD

**Issue by bugadani** [esp-rs/esp-hal#2273]
This could result in some funny behaviour if the user expect to loop back a GPIO into a peripheral, but the signal is not going through the GPIO matrix.

(For example, bitbanging SPI clock for slave loopback may not be output if the loopback pin is FSPICLK)

**Comment by Dominaezzz** [comment]
If I remember correctly you don't need the GPIO matrix for loopback/interconnect.

It should be fine for the output to go via io_mux and input to go via matrix, so long as the GPIO pad has both input and output enabled. (Which you have to do in the right order based on the current GPIO code)

**Comment by bugadani** [comment]
You kinda do, because you can't select two alternate functions for the same pin. I spent more time on this today than I'd like to admit.

**Comment by Dominaezzz** [comment]
Oh, I'd always thought of it as selecting an alternative function for the pin and an alternative function for the input signal, TIL
