### ISSUE TITLE
esp-wifi: Reduce logging level for normal timer operations.

### ISSUE THREAD

**Issue by AnthonyGrondin** [esp-rs/esp-hal#2282]
When building with log level `Debug`, the logs quickly get polluted by the following log lines. I believe, since they are normal operations, they should be degraded to trace level:

_*Note: I may be forgetting others, but these are the general ones I'm seeing_

https://github.com/esp-rs/esp-hal/blob/d3f03042f317f6e80c42c407015a0b452723c106/esp-wifi/src/compat/timer_compat.rs#L56-L59

https://github.com/esp-rs/esp-hal/blob/d3f03042f317f6e80c42c407015a0b452723c106/esp-wifi/src/compat/timer_compat.rs#L76

https://github.com/esp-rs/esp-hal/blob/d3f03042f317f6e80c42c407015a0b452723c106/esp-wifi/src/compat/timer_compat.rs#L109-L112

https://github.com/esp-rs/esp-hal/blob/d3f03042f317f6e80c42c407015a0b452723c106/esp-wifi/src/tasks.rs#L27

Example of the current logging:
```
DEBUG - timer_disarm 3fccf5e0
DEBUG - timer_disarm 3fccf5e0
DEBUG - timer_setfn 3fcce364 0x420f6b3c 0x0
0x420f6b3c - ieee80211_timer_process
    at ??:??
DEBUG - timer_setfn 3fcce378 0x420f6b3c 0x1
0x420f6b3c - ieee80211_timer_process
    at ??:??
DEBUG - timer_disarm 3fccf5e0
DEBUG - timer_disarm 3fccdb00 not found
DEBUG - timer_done 3fccdb00 not found
DEBUG - timer_setfn 3fccdb00 0x420e4260 0x0
DEBUG - timer_arm_us 3fccdb00 current: 1012271 ticks: 103000 repeat: false
DEBUG - timer_disarm 3fccf5e0
DEBUG - timer_disarm 3fccf5e0
DEBUG - timer_disarm 3fccf5e0
INFO - [AP] Wifi started
DEBUG - timer is due.... 3fccdb00
DEBUG - timer_disarm 3fccdb00
DEBUG - timer_arm_us 3fccdb00 current: 1135202 ticks: 83000 repeat: false
DEBUG - timer is due.... 3fccdb00
DEBUG - timer_disarm 3fccdb00
DEBUG - timer_arm_us 3fccdb00 current: 1235627 ticks: 85000 repeat: false
DEBUG - timer is due.... 3fccdb00
DEBUG - timer_disarm 3fccdb00
DEBUG - timer_arm_us 3fccdb00 current: 1334635 ticks: 88000 repeat: false
DEBUG - timer is due.... 3fccdb00

```

**Comment by bugadani** [comment]
Good point. In the mean time if you are using defmt, you should be able to use more targeted filters like `DEMFT_LOG="trace,esp-wifi=info`.
