### ISSUE TITLE
`embassy_interrupt_spi_dma`: C2, C3, C6, H2 - need to use a different DMA-enabled peripheral

### ISSUE THREAD

**Issue by tom-borcin** [esp-rs/esp-hal#2289]
Issue created from #1524

**Comment by bjoernQ** [comment]
I'm not quite sure what this issue is asking for. The mentioned targets only contain one GP-SPI

While it's technically possible to use SPI1 we don't support that and I'm not sure if we ever will or should (I'd personally say we shouldn't)

**Comment by bugadani** [comment]
The idea is to use I2S on these devices (or all of them).

**Comment by bjoernQ** [comment]
> The idea is to use I2S on these devices (or all of them).

Ok nice - C2 doesn't include I2S IIRC but at least this clarifies the issue a bit

**Comment by bugadani** [comment]
To be honest this is a bit of a non-issue anyway. With the Xtensas we have a test for both PDMA and GDMA devices and the original issue wasn't exactly device-specific.

**Comment by bjoernQ** [comment]
Hint: the PR which introduced the test is https://github.com/esp-rs/esp-hal/pull/2065
