### ISSUE TITLE
Wrong wrapping behavior in `Delay::delay` on riscv?

### ISSUE THREAD

**Issue by dimpolo** [esp-rs/esp-hal#229]
Given that `SystemTimer::now()` returns a 52bit timestamp the `wrapping_sub` seems wrong to me, but maybe I'm missing something :)
https://github.com/esp-rs/esp-hal/blob/3e4710b822d21f9673873757f8c3330e147065c6/esp-hal-common/src/delay.rs#L65-L71

**Comment by bjoernQ** [comment]
Yes seems like a problem to me

**Comment by MabezDev** [comment]
For reference I actually looked at fixing this a long while back, it might be a good reference to anyone wanting to take this on: https://github.com/esp-rs/esp-hal/commit/776a914cc521af253a6abe0bab3bfe9730a95d7d
