### ISSUE TITLE
move `WifiStack` to seperate crate or use a different stack

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#2299]
Feels a bit odd that it's included in esp-wifi itself, given that our/other BLE stack is separate.

I think we should either extract it, or consider another blocking stack to use for those examples.

**Comment by bjoernQ** [comment]
👍 definitely yes - in the very early days we used `smoltcp-nal` but it was notoriously behind the current smoltcp version and was/is (?) a bit lacking in terms of functionality (e.g. server sockets) .... probably worth to have another look or just move the code to somewhere for now

**Comment by Frostie314159** [comment]
In doing this, I'd suggest moving the phy init to a separate crate, since it's shared between all rf peripherals.

**Comment by bjoernQ** [comment]
> In doing this, I'd suggest moving the phy init to a separate crate, since it's shared between all rf peripherals.

Mind opening a separate issue for this?
