### ISSUE TITLE
regression: `esp_hal::init()` resets interrupts

### ISSUE THREAD

**Issue by kaspar030** [esp-rs/esp-hal#2386]
## Bug description

Since #2091, `esp_hal::init()` unconditionally disables all interrupts.

This broke our threading, as we set up the interrupt handler before, start threading, and then in a thread call `esp_hal::init()`. With #2091, this now disabled our scheduler interrupt again.

Resetting all interrupts might be actually acceptable behavior (probably most users call `esp_hal::init()` very early), but the PR#2091 decription only mentions an API rename, and the new behavior wasn't mentioned in the changelog.

(I'm slightly grumpy because we had to track this down but of course please don't read any blame. :wink:).

## To Reproduce

1. ...
2. ...

## Environment

- Target device: any xtensa
- Crate name and version: esp-hal 0.21.1

**Comment by bugadani** [comment]
Thanks, this will be fixed by https://github.com/esp-rs/esp-hal/pull/2377
