### ISSUE TITLE
esp-wifi: use even more ROM functions

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#2445]
strchr and strcat for example are available in ROM, but as part of newlib-funcs which I don't think we copied.

We can remove the need for many of the impls in `esp-wifi/src/compat/misc.rs` by using those and at the same time we should be able to remove the `have-strchr` feature as using `PROVIDE` should only use ROM function if it wasn't already defined by a third party crate (I think).

**Comment by bjoernQ** [comment]
True we can use more of these! - copy it all off newlib results in crashed but we can do it per function 

My understanding of PROVIDE is the same
