### ISSUE TITLE
Esp-wifi + rust-lld undefined symbol issue

### ISSUE THREAD

**Issue by BenCaunt** [esp-rs/esp-hal#2454]
## Bug description

When trying to build the esp32-wifi access point example there is an issue linking to several libraries by rust-lld.  The resulting error is here: https://gist.github.com/BenCaunt/a7a59c6e73099ea6e4c0548de6694d86

## To Reproduce

The issue seems to present itself when linking to this constructor:
```rust
let init: esp_wifi::EspWifiInitialization = init(
    EspWifiInitFor::Wifi,
    timg0.timer0,
    Rng::new(peripherals.RNG),
    peripherals.RADIO_CLK,
)
.unwrap();
```
removing this from the code results in it compiling successfully.

This particular commit has the minimum code I needed to reproduce the issue.  I am compiling on arm and had the issue occur both in MacOS and on Ubuntu.  
https://github.com/ChillyCoyote273/meltybrain/commit/26ef6817ce3f16dc46509dd00e351b324fa17e3f

## Expected behavior
Successful compilation of the project

## Environment
Target is the esp32c3.  The issue happens during building.  
esp-hal = { version = "0.21.1", features = [ "esp32c3" ] }
esp-wifi = { version = "0.10.1", features = ["esp32c3", "wifi-default", "wifi", "utils", "phy-enable-usb", "embassy-net", "esp-alloc"] }

**Comment by bugadani** [comment]
You'll need to add `println!("cargo:rustc-link-arg-bins=-Trom_functions.x");` to your `build.rs`.

You can find a few important pieces of information in the [documentation](https://docs.esp-rs.org/esp-hal/esp-wifi/0.10.1/esp32c3/esp_wifi/#link-configuration).
