### ISSUE TITLE
Preliminary I2S Support

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#247]
- starting with ESP32-C3 and ESP32-S3
- then ESP32 and ESP32-S2
- for the start just the TX channel
- for the start just standard I2S

**Comment by brainstorm** [comment]
Kudos! Is there an active branch I can look at for this work?

**Comment by bjoernQ** [comment]
> Kudos! Is there an active branch I can look at for this work?

I pushed the current WIP here: https://github.com/bjoernQ/esp-hal/tree/feature/i2s ... it's still a lot to do

**Comment by brainstorm** [comment]
Thanks!

This work is now tangentially related: https://github.com/embassy-rs/embassy/pull/1049

Since I just noticed https://github.com/esp-rs/esp-hal/pull/225 :)
