### ISSUE TITLE
Implement MultiwriteNorFlash marker trait on esp-storage::FlashStorage

### ISSUE THREAD

**Issue by yanshay** [esp-rs/esp-hal#2473]
## Motivations

`embedded-srorage` defined this trait and various crates are using it (`sequential-storage`).
w/o it these crates can't be used.
from https://github.com/esp-rs/esp-storage/issues/39 it seems esp32 flash supports the functionality represented by this trait.
I can do that myself and submit a PR but want to verify this is indeed the case.

## Solution

Just add the mentioned trait to FlashStorage (when `nor-flash` feature toggle is enabled)

**Comment by bjoernQ** [comment]
Yes implementing the `MultiwriteNorFlash` marker should be fine for all our chips

**Comment by yanshay** [comment]
Submitted PR #2478

**Comment by Dominaezzz** [comment]
PR was merged
