### ISSUE TITLE
Tracking the "next" project

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#249]
This work is inspired largely by the same effort already undergone in `esp-idf-hal`, which in turn was based on the work done in `embassy`.

https://github.com/esp-rs/esp-idf-hal  
https://github.com/embassy-rs/embassy  

Development will be done in the `next` branch. I have added a single commit which adds some types, traits, and macros which will be required for development.

https://github.com/esp-rs/esp-hal/tree/next

This branch will be periodically rebased on `main` to keep it in sync as much as possible. As we're able we can merge changes into `main`, repeating this until the process is complete.

A number of peripherals will need their high-level interfaces re-written, though we can likely take this directly from `esp-idf-hal` with only minor modification. Hopefully most of the low-level code can be kept and/or adapted.

## Tasks

The tasks below do _not_ need to be completed in any particular order.

**If you plan to implement the necessary updates for a peripheral please leave a comment below indicating such.**

- [x] ADC (#321)
- [x] ClockControl (#316)
- [x] DAC (#321)
- [x] DMA (#317)
- [x] GPIO (#323)
- [x] I2C (#303)
- [x] I2S (#313)
- [x] LEDC (#307)
- [x] MCPWM (#314)
- [x] RMT (#310)
- [x] RNG (#306)
- [x] RTC (#319)
- [x] SHA (#312)
- [x] SPI (#299)
- [x] SYSTEM (#305)
- [x] SYSTIMER (#302)
- [x] TIMG (#320)
- [x] TWAI
- [x] UART (#272)
- [x] USB_OTG (#318)
- [x] USB_SERIAL_JTAG (#304)

**Comment by jessebraham** [comment]
I have previously done some work on both the `UART` and `GPIO` modules, and will get both projects cleaned up and pushed to branches soon.

**Comment by jessebraham** [comment]
With #272 merged we have all the required building blocks to move forward with this, plus a `UART` implementation for reference.

**Comment by bjoernQ** [comment]
For reference: #299 is a good example what needs to be done to convert a peripheral driver to the use the PeripheralRef pattern

**Comment by MabezDev** [comment]
Working on SYSTIMER

**Comment by jessebraham** [comment]
Working on I2C

**Comment by SergioGasquez** [comment]
Working on USB

**Comment by jessebraham** [comment]
Have `RNG` finished locally (will PR tomorrow) and then I'll tackle `SHA` after that.

**Comment by bjoernQ** [comment]
Working on SYSTEM/DPORT

**Comment by MabezDev** [comment]
Working on LEDC ☠️

**Comment by bjoernQ** [comment]
Working on ClockControl

**Comment by MabezDev** [comment]
Working on MCPWM

**Comment by bjoernQ** [comment]
Working on DMA

**Comment by bjoernQ** [comment]
Working on USB_OTG

**Comment by bjoernQ** [comment]
Working on RTC

**Comment by bjoernQ** [comment]
no idea what to do about TWAI since it's not merged yet 🤷‍♂️

**Comment by bjoernQ** [comment]
Looking into GPIO

**Comment by jessebraham** [comment]
> no idea what to do about TWAI since it's not merged yet 🤷‍♂️ 

I am going to try and get a test project set up for this next week so that we can get that PR merged.

**Comment by jessebraham** [comment]
Have I missed any peripherals in the first post? I will go through the code base later, but wouldn't mind some more eyes on it just to be sure.

**Comment by jessebraham** [comment]
`TWAI` PR has been merged, so I suppose we're done here 😁 Thanks for the help everybody!
