### ISSUE TITLE
Remove `get_` prefixes from all functions

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#2524]
There are a number of functions, public or otherwise, which still have the `get_` prefix. This violates the [suggested naming conventions](https://rust-lang.github.io/api-guidelines/naming.html) laid out by the Rust API Guidelines, and as such they should be removed.

@MabezDev would you like me to tackle this before the next release, or wait until after we've published `0.22.0`?

**Comment by MabezDev** [comment]
Let's get this out of the way and do it now, I hope it should be fairly straight forward.
