### ISSUE TITLE
[ESP32-S2] LoadStore exception with systimer timer on embassy_hello_world example

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#253]
Found when testing https://github.com/esp-rs/esp-hal/pull/225, seems unrelated to the PR but could be an issue with atomic emulation (or a codegen issue)

**Comment by MabezDev** [comment]
Seems like with 1.67, this is no longer an issue.

**Comment by bugadani** [comment]
cc https://github.com/embassy-rs/embassy/pull/1962
