### ISSUE TITLE
esp-wifi: wrong size event data

### ISSUE THREAD

**Issue by denysvitali** [esp-rs/esp-hal#2611]
## Bug description

esp-wifi `0.11.0` seems to panic when `scan_n()` is called.

```plain
====================== PANIC ======================
panicked at /home/user/cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-wifi-0.11.0/src/wifi/event.rs:193:5:
assertion `left == right` failed: wrong size event data
  left: 8
 right: 0
```

It looks like there has been a recent change (#2453 ) to esp-wifi:
https://github.com/esp-rs/esp-hal/blame/b06c7a470c0242eace7d5ef616a3ccbad4d52239/esp-wifi/src/wifi/event.rs#L196

This is an example on how I'm trying to use `scan_n`:

```rust
    controller.start().unwrap();
    esp_println::println!("is wifi started: {:?}", controller.is_started());

    esp_println::println!("Start Wifi Scan");
    let res: Result<
        (heapless::Vec<esp_wifi::wifi::AccessPointInfo, 10>, usize),
        esp_wifi::wifi::WifiError,
    > = controller.scan_n();
    if let Ok((res, _count)) = res {
        for ap in res {
            esp_println::println!("{:?}", ap);
        }
    }
```

and it results in the above error, after passing all the other lines:
```
wifi_set_configuration returned Ok(())
is wifi started: Ok(true)
Start Wifi Scan
```

Following is a partial backtrace:
```
0x4201453e
0x4201453e - core::panicking::assert_failed
    at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:367
0x4200bd20
0x4200bd20 - esp_wifi::wifi::event::dispatch_event_handler
    at ??:??
```

This happens on an ESP32-C3

## To Reproduce

1. Try to use `scan_n` on an ESP32-C3, using `esp-wifi` `0.11.0`
2. The application will panic

## Expected behavior

The list of APs is returned and the application doesn't panic.

## Environment

- ESP32-C3
- esp-wifi `0.11.0`

**Comment by bjoernQ** [comment]
There was indeed a problem, but it should only fail when compiling with `debug-assertions` enabled.
Compiling in `debug` mode is not recommended - did you manually enable `debug-assertions`?

**Comment by denysvitali** [comment]
I didn't, but I was running in debug mode (therefore I assume that debug assertion were enabled because of that)

**Comment by bjoernQ** [comment]
> I didn't, but I was running in debug mode (therefore I assume that debug assertion were enabled because of that)

Thanks for the reply - that explains it. Just using `release` (which is highly recommended) will make it work - while the assert is technically correct nothing bad will happen

**Comment by denysvitali** [comment]
Confirmed. I feel so stupid for not thinking about this earlier :facepalm:. Thanks!

**Comment by bjoernQ** [comment]
No worries! This uncovered a weakness in our testing so it's a good thing 👍
