### ISSUE TITLE
Remove the prelude

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#2660]
It's shrunk considerably in the last year or two, maybe we can get away without having one at all?

**Comment by bjoernQ** [comment]
I'd say let's remove it - the only "ugly" things are extension traits like `fugit::RateExtU32`

**Comment by jessebraham** [comment]
I generally agree that it's not necessarily required, but forcing users to add `fugit` as a dependency to every project using the HAL is also  going to be kind of a pain.

**Comment by bjoernQ** [comment]
Even if it's not in the prelude we could still re-export Fugit's extension traits (when it's 1.x)

**Comment by MabezDev** [comment]
Given that we mind end up removing `fugit` if it's not stable in time, and based on the discussion here, I think we should try to remove the prelude.
