### ISSUE TITLE
Pin drivers should take a `Config` struct instead of `Pull` or `Level` directly.

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#2696]
With the builder lite derive this should be quite nice `Config::default().with_level()`

**Comment by bugadani** [comment]
I'd like to mark this as a duplicate - even though #2708 came later, it also includes that the constructors should return a Result - which is generally not that important, but can prevent ESP32 from panicking.

**Comment by bjoernQ** [comment]
fine - since the other issue will keep the link to this
