### ISSUE TITLE
Allow enabling/disabling cts/rts via `Config`

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#2731]

**Comment by bugadani** [comment]
Does this issue refer to enabling hardware flow control in general, or the "software-control of hardware flow control lines" feature? I think, for the latter, `apply_config` may be a slightly heavy-handed approach.

**Comment by MabezDev** [comment]
I opened this specifically for the enable/disable of hardware flow control, for example where a user sets up flow control pins during construction but wants to switch between enabling/disabling it at run time.

**Comment by bugadani** [comment]
Generally supporting flow control is already tracked [here](https://github.com/esp-rs/esp-hal/issues/2644).

**Comment by MabezDev** [comment]
Oops, thanks!
