### ISSUE TITLE
Private details should not leak into the public API

### ISSUE THREAD

**Issue by bugadani** [esp-rs/esp-hal#2766]
Depends whether we consider `State`, `Info` and `Instance` private. They are public and not hidden. `Info` exposes the `RegisterBlock` and `system::Peripheral` enum - which is necessary if we consider `Info` part of a public, low-level API. The resolution of this point should also be reflected in the API-GUIDELINES under `Driver implementation`, as a clarification.

**Comment by bugadani** [comment]
Also includes

- #2697

**Comment by bjoernQ** [comment]
We all agree to doc-hide `State`, `Info` and `Instance`?

**Comment by MabezDev** [comment]
> We all agree to doc-hide `State`, `Info` and `Instance`?

Yes. Could you amend the guidelines to do that for new drivers too?

**Comment by bugadani** [comment]
Added a clarification to https://github.com/esp-rs/esp-hal/pull/2832
