### ISSUE TITLE
Compiler Warning: unreachable pattern

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#282]
```
warning: unreachable pattern
   --> C:\projects\esp\esp-hal\esp-hal-common\src\sha.rs:295:13
    |
295 |             _ => 128,
    |             ^
    |
    = note: `#[warn(unreachable_patterns)]` on by default
```

**Comment by jessebraham** [comment]
Yeah sorry, I was aware of this and let it through anyways. Just affecting the C-series sounds correct to me.

**Comment by bjoernQ** [comment]
No problem - I'd be even fine with an `#[allow(..)]` for that code block - it's just that compiler warnings are somewhat annoying in such a crate
