### ISSUE TITLE
Missing documentation for crates besides esp-(idf-)hal and esp-wifi

### ISSUE THREAD

**Issue by Be-ing** [esp-rs/esp-hal#2857]
## Bug description

This repository has a variety of crates in it, but only documentation for esp(-idf)-hal and esp-wifi are published on https://docs.esp-rs.org/esp-hal/ The other crates are failing to build on docs.rs with a variety of errors, for example:

https://docs.rs/crate/esp-hal-smartled/0.13.0/builds/1341613
https://docs.rs/crate/esp-idf-servo/0.2.4/builds/842060

**Comment by bugadani** [comment]
We host documentation for the crates that have differences based on the chips you might use. This does not include community maintained crates like esp-hal-smartled, or esp-idf based crates.
