### ISSUE TITLE
Document all packages and peripherals

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#29]
It's that job nobody wants to do!

This is a long-term project, as there's not much point documenting drivers until their interfaces are relatively stable.

Each HAL package should have top-level documentation at the very least. Peripheral drivers should additionally be documented, preferably even containing simple examples as doc tests.

---

Beginning with module-level documentation, here are all modules which are currently exported by any of the chip-specific HAL packages:

- [x] adc
- [x] aes
- [x] analog
- [x] assist_debug
- [x] clock
- [x] cpu_control
- [x] dac
- [x] delay
- [x] dma
- [x] efuse
- [x] esp_riscv_rt
- [x] gpio
- [x] i2c
- [x] i2s
- [x] interrupt
- [x] ledc
- [x] lp_core
- [x] macros
- [x] mcpwm
- [x] otg_fs
- [x] pcnt
- [x] peripheral
- [x] peripherals
- [x] prelude
- [x] psram
- [x] radio
- [x] reset
- [x] rmt
- [x] rng
- [x] rom
- [x] rsa
- [x] rtc_cntl
- [x] sha
- [x] spi
- [x] system
- [x] systimer
- [x] timer
- [x] trapframe
- [x] twai
- [x] uart
- [x] ulp_core
- [x] usb_serial_jtag

**Comment by IshanDaga** [comment]
Hi Jesse, 
New to Rust, though I have been using the ESP-IDF for the last 15 or so months.

I'd like to be able to contribute to this project and learn rust while I'm at it - is this a good place to start?

**Comment by jessebraham** [comment]
@IshanDaga if you are willing to work on this then yes, that would be awesome! This is definitely one of our weaker points currently so it'd be great to improve this.

In general (with the exception of the `chip support` label) any open issue is fair game; if it's assigned to somebody already just ask if they're actively working on it, there's a good chance they are not and that you can take it over 😁

**Comment by jessebraham** [comment]
I've documented the `Rng` peripheral in #650, which can be loosely used as a model for other peripherals. @playfulFence is also working on a number of drivers' documentation.

**Comment by jessebraham** [comment]
With #680 merged I'm happy to call this "done". There is of course more work to do, but all packages and modules have at least some documentation now.
