### ISSUE TITLE
Add git pre-commit hooks to check formatting

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#298]

**Comment by igrr** [comment]
In case this helps, here are the ones I have been using: https://github.com/igrr/notred/blob/main/.pre-commit-config.yaml

**Comment by bjoernQ** [comment]
Seems like rust-analyzer used something like an `xtask` for it but it also seems they don't do it anymore
The relevant PR in rust-analyzer was https://github.com/rust-lang/rust-analyzer/pull/271

I think ideally, we shouldn't rely on tools written in Python (for bare-metal) - on the other hand it's just an offer to users so it might be okay

**Comment by jessebraham** [comment]
My mistake, I didn't even realize that Python tool existed. I thought the original comment in the PR was referring to the standard shell script git hooks.
