### ISSUE TITLE
Docs failing for `esp-common-hal`

### ISSUE THREAD

**Issue by elpiel** [esp-rs/esp-hal#340]
`esp-hal-common` last build - https://docs.rs/crate/esp-hal-common/0.4.0/builds/699614, fails with:

```
[INFO] [stderr]   process didn't exit successfully: `/opt/rustwide/target/debug/build/esp-hal-common-0b780ac360c2e547/build-script-build` (exit status: 101)
[INFO] [stderr]   --- stderr
[INFO] [stderr]   thread 'main' panicked at 'Exactly 1 chip must be enabled via its Cargo feature, 0 provided', build.rs:12:14
```

**Comment by jessebraham** [comment]
This is expected, without specifying a chip (and some other features) the crate will not build. There is not much sense is building it for only a single chip as that doesn't really provide any utility to anybody, IMO.

The docs are re-used by the chip-specific packages via the `#[inline]` attribute, so anything re-exported from `esp-hal-common` via those package will be documented by those packages' docs.
