### ISSUE TITLE
Traits with private bounds.

### ISSUE THREAD

**Issue by strongwar** [esp-rs/esp-hal#345]
```
pub struct Lcd<T,TX,RX>
where
    T: esp32_hal::prelude::_esp_hal_spi_InstanceDma<TX, RX>,
    TX:esp32_hal::dma::private::Tx, 
    RX:esp32_hal::dma::private::Rx,
{
    spi: T,
    fch: u8,
    fcl: u8,
}
```

I am trying to define a struct that holds a SpiDma struct, however, when I try to set its traits I can't since the TX and RX traits require private bounds. Is there a way to get around this?

**Comment by bjoernQ** [comment]
Probably we were too strict here and the traits should be made public

Another user (on Matrix chat) also ran into this before

We are always happy to receive a PR - I can also look into this but currently I am a bit busy with something else so it might take some time
