### ISSUE TITLE
Rewrite chip startup code in assembly

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#363]
See https://github.com/rust-embedded/cortex-m-rt/issues/300 for me details.

The TLDR version is, we shouldn't be calling any Rust until data/bss and properly initialized. `asm!` is stable so we should just do it :)

**Comment by bjoernQ** [comment]
Relevant issues
- https://github.com/esp-rs/xtensa-lx-rt/issues/53
- https://github.com/esp-rs/esp-riscv-rt/issues/1

**Comment by jessebraham** [comment]
There's a tracking issue in `xtensa-lx` already for this, so going to close this issue since there's nothing left to do once that's updated.
