### ISSUE TITLE
Add support for the RISC-V ULP

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#377]
A number of devices contain a RISC-V LP/ULP co-processor: ESP32-C6, ESP32-S2, and ESP32-S3 (with more likely coming in the future). These cores execute independently of the main CPU core(s), and require their own HALs.

- [x] Create SVDs for each RISC-V LP/ULP
- [x] Create PACs for each RISC-V LP/ULP
- [ ] Create new procmacros for each RISC-V LP/ULP
    - [x] ESP32-C6
    - [ ] ESP32-S2
    - [ ] ESP32-S3
- Create HALs for each RISC-V LP/ULP
    - [x] ESP32-C6
    - [ ] ESP32-S2
    - [ ] ESP32-S3 

In addition to the HALs themselves, we will also likely need some startup/runtime code (analogous to `riscv`/`esp-riscv-rt` plus the necessary machinery for actually building and loading the application to the ULP core. This can likely be accomplished via a build script.

- [ ] Implement the necessary support library(ies) for building and flashing the application to the LP/ULP core

**Comment by jessebraham** [comment]
I have begun work on the lower-level aspects of adding support for the ESP32-S2/S3: I have created initial versions of their SVDs and am able to generate PACs from these.

The next step is to load a basic application to the RISC-V ULP core and execute it. I unfortunately have not yet been successful with this, but hopefully once we start working on this project again we can get to this point without too much hassle.

**Comment by jessebraham** [comment]
SVDs and PACs have been created for the ESP32-C6's LP core and the ESP32-S2/S3's ULP cores.

**Comment by bjoernQ** [comment]
Initial work on ESP32-C6 LP core is started in https://github.com/bjoernQ/esp32c6lp-hal - as soon as we are confident enough it's heading into the right direction the code will get moved to the esp-hal repo

**Comment by jessebraham** [comment]
#714, #715, and #720 have begun work on the `esp32c6-lp-hal` package in this repository. More features to come.

**Comment by bjoernQ** [comment]
Started working on S2/S3 ULP HAL. Initial version might not support any peripherals (depends on the progress I make) but will enable us to compile Rust code to run on the ULP

**Comment by jessebraham** [comment]
I think we can probably close this, we have `esp32c6-lp-hal` and `esp-ulp-riscv-hal` packages now, and while not feature complete they are present and functional; enough to build on top of, at least. I think it would be better if we opened more, finer-grained issues instead.

So, gonna close this. If anybody has any objections we can re-open the issue.

**Comment by maufl** [comment]
Is there an minimal example on how to use these crates? I have successfully written a small Rust program for my ESP32-C6 and now I'd like to include a program for the (U)LP co-processor. The `exp32c6-lp-hal` crate has examples, but I don't know how to build them, include them when flashing and how to load them from my main program.

**Comment by MabezDev** [comment]
We have examples using the LP core in the top level examples folder: https://github.com/esp-rs/esp-hal/blob/5d6354ccbd62527452968074c4a92a4fc6c6a635/examples/src/bin/lp_core_basic.rs#L33-L43

**Comment by maufl** [comment]
Perfect! This is exactly what I was looking for, and such a fast response time :star_struck: Thank you very much :pray:

**Comment by jessebraham** [comment]
I do also plan on spending some time further developing the low-power HAL in the near future. Probably not this release cycle, but possibly the next. This will include more/better documentation as well, I hope to make the process a bit easier.
