### ISSUE TITLE
Consider increasing default stack sizes

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#378]
Whilst debugging some unrelated esp-wifi issues, I found at times the stack depth almost exceeded the default stack sizes inside we should think about increasing it.

**Comment by bugadani** [comment]
Can this issue be closed now? Unfortunately, "addresses" is not a special closing word on github, but bjoern's PR description was clear enough I think.

**Comment by bjoernQ** [comment]
Oh .... just forgot to close this. Thanks!
