### ISSUE TITLE
Destructors don't run on panic

### ISSUE THREAD

**Issue by dimpolo** [esp-rs/esp-hal#380]
The destructor of `NoisyDrop` does not run.

```rust
#![no_std]
#![no_main]

use esp32s3_hal::{
    clock::ClockControl, peripherals::Peripherals, prelude::*, timer::TimerGroup, Rtc,
};
#[allow(unused_imports)]
use esp_backtrace as _;
use esp_println::println;

use xtensa_lx_rt::entry;

#[entry]
fn main() -> ! {
    let peripherals = Peripherals::take();
    let system = peripherals.SYSTEM.split();
    let clocks = ClockControl::boot_defaults(system.clock_control).freeze();

    let mut rtc = Rtc::new(peripherals.RTC_CNTL);
    let timer_group0 = TimerGroup::new(peripherals.TIMG0, &clocks);
    let mut wdt = timer_group0.wdt;

    // Disable MWDT and RWDT (Watchdog) flash boot protection
    wdt.disable();
    rtc.rwdt.disable();

    let _noise = NoisyDrop;
    panic!();
}

struct NoisyDrop;

impl Drop for NoisyDrop {
    fn drop(&mut self) {
        println!("noise");
    }
}
```

I noticed this, when the second core continued running when the first on panicked even though a dropped `AppCoreGuard` should have stopped it.

**Comment by bjoernQ** [comment]
Thanks for bringing this up.

I _think_ to make this work we would need to implement unwinding which is not easy and not really common on embedded targets but what we could and probably should do in `esp-backtrace`'s panic-handler is to halt all cores - not just the one that panicked.

**Comment by dimpolo** [comment]
Ah, so unwinding currently just isn't implemented at all? I guess that would make sense also from a binary size perspective.

> what we could and probably should do in esp-backtrace's panic-handler is to halt all cores - not just the one that panicked.

That would be great!

**Comment by bjoernQ** [comment]
I created an issue for that in the `esp-backtrace` repo: https://github.com/esp-rs/esp-backtrace/issues/19

**Comment by jessebraham** [comment]
Do we just need to publish a new release of `esp-backtrace` to close this issue, or is there any additional work to be done?

**Comment by bjoernQ** [comment]
> Do we just need to publish a new release of `esp-backtrace` to close this issue, or is there any additional work to be done?

Yes - it's already implemented and we just need a release (we also want one for C6 support)
