### ISSUE TITLE
esp32s3 usb_serial.rs example not working

### ISSUE THREAD

**Issue by PocketPi** [esp-rs/esp-hal#495]
When i try to setup the usb_serial.rs example it first of all do not compile. 

I have to modify the arguments given to TimerGroup::new. I have to remove third argument: &mut system.peripheral_clock_control,

When i then build it and flash it and plug it into my pc the usb port is not showing up and i get a lot of usb errors. 

When looking a bit more in the code it looks like the usb_dp and usb_dm are swapped, im using a T-Displat-S3 from Lilygo, but it also looks like the esp32-s3-devkit-c is having the same pinout: https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1.html

Can anyone help me figure out how to fix the issue?

**Comment by bjoernQ** [comment]
Regarding the problems compiling it: You probably didn't run the example inside the repo? There is a breaking change regarding the TimerGroup initialization

It definitely worked before but I can confirm it stopped working

We need to check which commit broke it

**Comment by PocketPi** [comment]
Correct i have used the template generator tool to make a new project and then copied the code to the generated project

**Comment by PocketPi** [comment]
the compiling issue was introduced with this pr: https://github.com/esp-rs/esp-hal/pull/463

**Comment by bjoernQ** [comment]
@MabezDev this is a Rust compiler issue apparently .... it works (even with current main) with the Xtensa-enabled Rust compiler 1.65 and 1.66 but not with 1.67, 1.68 or 1.69 👻

**Comment by PocketPi** [comment]
I also think that there is a problem with the crate, i can see in you example that you point directly to github and that you do not just let cargo get it from the crates registry

**Comment by bjoernQ** [comment]
> I also think that there is a problem with the crate, i can see in you example that you point directly to github and that you do not just let cargo get it from the crates registry

Yes, at the time of writing that example we haven't had a release of esp-hal including usb-device support yet
