### ISSUE TITLE
No way to update bus clock frequency of an SpiDma instance

### ISSUE THREAD

**Issue by bugadani** [esp-rs/esp-hal#518]
`Spi` has a `change_bus_frequency` function to update SCLK frequency. When using DMA, however, the `SpiDma` wrapper does not currently allow access to this function and users are stuck with the original clock speed as it's not possible to deconstruct the driver or to access the internal Spi object.

**Comment by hsteinhaus** [comment]
Is it possible that there is a regression in v1.0.0 now? Grep for `change_bus_frequency` only yields the Changelog entry from 2023. Alternatively, an (undocumented) change to a different way?

**Comment by MabezDev** [comment]
Since 1.0 we use a config struct instead of individual setters. What you're looking for is here: https://docs.espressif.com/projects/rust/esp-hal/1.0.0/esp32c6/esp_hal/spi/master/struct.Config.html#method.with_frequency
