### ISSUE TITLE
[ESP32-H2] Add the `rng` example

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#575]
The bootloader still lacks the proper support for initializing the `RNG` peripheral, so we are not able to get any meaningful output and as such are opting not to include the example at this time. Once the bootloader is updated we can add this example.

**Comment by MabezDev** [comment]
We should probably look at adding RNG initialization code in esp-hal for all chips, we currently rely on the esp-idf bootloader to do it, which might not always be available with direct-boot etc.

**Comment by jessebraham** [comment]
Closed by #591
