### ISSUE TITLE
Add a `rt` feature to the hals

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#579]
It should be entirely possible to build the hal without the rt feature, but they currently do not.

**Comment by MabezDev** [comment]
It seems the  `rt` feature is always enabled on the pacs, and the runtimes seems to be enabled always. We need to add a feature.

**Comment by jessebraham** [comment]
This is actually non-trivial due to the tight coupling between:

- `esp-hal-common` and `esp-riscv-rt` via the `TrapFrame` struct
- `esp-hal-common` and `xtensa-lx-rt` via the `Context` struct

Both of these are required for our interrupt handling.

Other than pulling `TrapFrame`/`Context` out into their own package(s) (which I'm not super excited about doing) I'm not sure how best to approach this.

**Comment by jessebraham** [comment]
Ahh yeah you're probably right, didn't even think of that. I also forget why @MabezDev wanted this, so maybe a reminder is in order? 😅

**Comment by MabezDev** [comment]
The problem isn't cfging away the interrupt stuff when we don't enable the rt feature, its actually the inverse. When enabling the `rt` feature there doesn't currently seem to be a way to only enable _either_ `esp-riscv-rt` _or_ `xtensa-lx-rt` to get the trap frame. I think whilst we were in Brno we even tried to do it with a build script but that doesn't work because the script is executed after dep resolution.

Maybe we can just enable both? It might hurt build times (not by much at all though, both are very, very small crates) but won't actually do anything unless we include it in our code; which when `rt` is not enabled will be the case. What do you think?

**Comment by bjoernQ** [comment]
I think we would try to compile e.g. the RISCV Assembly with the Xtensa target and vice versa, then?
Since we control both `rt` crates we would need to `cfg` - gate that code depending on the `target_arch` to solve that 🤔

**Comment by MabezDev** [comment]
Maybe another option I just thought of, we could just push this feature resolution to the actual hal crates, instead of having the logic inside esp-hal-common. I.e `esp32c3-hal` would enable the `esp32c3` feature of esp-hal-common, but also `esp-riscv-rt`, same goes for the other chips/archs.
