### ISSUE TITLE
[ESP32-H2] Add the `adc_cal` example

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#634]
Per [this comment](https://github.com/esp-rs/esp-hal/pull/555#issuecomment-1620556430):

> Because esp-idf still does not support calibration for H2 so I don't know how we can add support for it just now. (see [efuse/esp32h2/esp_efuse_rtc_calib.c#L13](https://github.com/espressif/esp-idf/blob/903af13e847cd301e476d8b16b4ee1c21b30b5c6/components/efuse/esp32h2/esp_efuse_rtc_calib.c#L13))

**Comment by MabezDev** [comment]
Let's track this in https://github.com/esp-rs/esp-hal/issues/326 instead.
