### ISSUE TITLE
Add Example for using the touch_pad

### ISSUE THREAD

**Issue by Angr1st** [esp-rs/esp-hal#644]
Hi esp-rs team,
I was wondering If you would be willing to create an example that showcases how to use the touch_pads of the esp32, as I was unable to find any sample code for that. 
I would otherwise be happy for any pointer in the right direction to get going with it. 

Thanks for the hard work.

**Comment by bjoernQ** [comment]
We don't have touch sensing support, yet.

If someone is looking into implementing it, besides the TRM the ESP-IDF code ( https://github.com/espressif/esp-idf/tree/master/components/driver/touch_sensor ) might be a good starting point.
