### ISSUE TITLE
Periodic interrupts every 100ns

### ISSUE THREAD

**Issue by elkel53930** [esp-rs/esp-hal#685]
Hello,

I am trying to utilize periodic interrupts every 100ns (10MHz) using the ESP32S3. However, looking at the set_period() function in SystemTimer, it appears that the maximum frequency is limited to 1kHz. Is there a specific reason for this? Additionally, is there a way to achieve interrupts every 100ns?

Thank you.

**Comment by bugadani** [comment]
You should look at the other timer peripherals, but honestly, I'm not sure what you can do with 24 CPU cycles, even if you have an other core to work with.

**Comment by elkel53930** [comment]
Sorry, it is 100us, not 100ns.

**Comment by elkel53930** [comment]
@MabezDev Thanks for the advice. I will give it a try.
