### ISSUE TITLE
Hooks for Linker Script Configuration

### ISSUE THREAD

**Issue by jamesmunns** [esp-rs/esp-hal#703]
Hey all! In https://github.com/tosc-rs/mnemos/issues/206, we are looking at the "right" way to determine how much memory we have available for the heap and stack, and would like to add some basic asserts to "reserve" an amount of space for the heap and stack, so that we get a linker error if we run out of memory room due to too many statics, etc.

the cortex-m-rt platform allows the user to set some extra variables in `memory.x`, as well as add your own link time asserts.

Right now, the esp-hal linker scripts are directly generated by the build.rs in this repo, and other than selecting the operational mode, gives the user no ability to customize the linker script. Additionally there is some logic in the linker script for setting the heap start and reserving size for it - but the heap size is PROVIDE'd to zero.

We could always just use our own full linker script, but it would be nice to be able to say "please make sure there is at least 128KiB for heap and 64KiB for stack" without completely discarding the upstream linker scripts.

CC @hawkw

**Comment by MabezDev** [comment]
This is likely to be implemented via a configuration of some kind, so I'm closing this in favour of #1111
