### ISSUE TITLE
**esp-hal-common** build.rs should check `device.symbols` for psram (?)

### ISSUE THREAD

**Issue by jsosulski** [esp-rs/esp-hal#717]
Not sure if correct, but currently the `build.rs` script in the common hal checks device.peripherals for a `"psram"` entry, which is not defined for any of the devices. Should `device.symbols` be checked instead / in addition?

**Comment by bjoernQ** [comment]
You are right. Should be symbols

Seems this was caused by a refactoring a few weeks ago
