### ISSUE TITLE
`smart_leds_adapter` should take a rate instead of assuming `rmt` to be configured in a special way

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#74]
Currently `smart_leds_adapter` assumes the `pulse_control` is configured to 40Mhz - easiest solution would be to take a rate which the user should have configure for the `pulse_control`

**Comment by bjoernQ** [comment]
Not sure how relevant this is anymore since ideally the SmartLeds stuff should get moved into its own crate some day

see https://github.com/esp-rs/esp-hal/pull/252

**Comment by bjoernQ** [comment]
Probably the easiest would be to just explicitly state in the API docs of smart_leds_adapter that the user needs to specify exactly 80MHz and we can close this

**Comment by jessebraham** [comment]
I guess with #1154 merged this is no longer relevant, so closing.
