### ISSUE TITLE
ESP32-C6 unable to use ADC on GPIO5

### ISSUE THREAD

**Issue by georgik** [esp-rs/esp-hal#769]
How to simulate: 
Take ADC exmaple from esp-hal, change GPIO to 5.

Result:
Crash in runtime with message `index out of bounds: the len is 5 but the index is 5`

Reason:
The number of ADC is hard-coded and that's not true for all targets supported by esp-hal

Workaround:
Switch to GPIO2

**Comment by jessebraham** [comment]
I think the issue lies here:  
https://github.com/esp-rs/esp-hal/blob/main/esp-hal-common/src/analog/adc/riscv.rs#L540

The size of this array changes depending on the chip I suppose.
