### ISSUE TITLE
Enabling the `ufmt` feature has no effect

### ISSUE THREAD

**Issue by bugadani** [esp-rs/esp-hal#772]
The `ufmt` feature is defined and documented, but I don't see it used anywhere in code.

**Comment by bjoernQ** [comment]
It enables the impl of `uWrite` for `Uart`and `UsbSerialJtag` but I agree that's not what I would expect from such a feature.
Probably we should more generally use it or drop it 🤷‍♂️

**Comment by bugadani** [comment]
> It enables

if it does, my setup is seriously broken, I searched for `feature = "ufmt"` and vscode didn't give me anything 👀
