### ISSUE TITLE
Find an alternative for the `dangoslen/changelog-enforcer@v3` action

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#775]
This has been driving me insane for months now, it needs to be replaced.

**Comment by bjoernQ** [comment]
Is it just this issue: https://github.com/dangoslen/changelog-enforcer/issues/176 ?

Or are the other things we want to be different?

**Comment by jessebraham** [comment]
It's mostly just the fact that if you don't add the `skip changelog` label when you create your PR, adding it after the fact as has no effect and we're forced to merge with red CI.

**Comment by romancardenas** [comment]
As mentioned in [this PR](https://github.com/rust-embedded/riscv-rt/pull/124), perhaps you can fix this by isolating the Changelog job in a different workflow and configuring it to re-run whenever you add/remove labels to a PR.
