### ISSUE TITLE
no_std issue with esp32c6-hal

### ISSUE THREAD

**Issue by blue-freedom-technologies** [esp-rs/esp-hal#778]
We have no issues creating and flashing  std rust applications.

But when we create a no_std it does not work.

As an example, we have create a hello-world based in the [esp-template](https://github.com/esp-rs/esp-template), and it becomes stuck indefinitely.

![image](https://github.com/esp-rs/esp-hal/assets/142290531/d730cedf-0e3b-43f0-87b1-069649ba421d)

Any advise would be welcome.

Cheers,

**Comment by JurajSadel** [comment]
Hello @blue-freedom-technologies! I just tried creating a new C6 project and it works fine for me. Could you please provide us with more information like what exact options you use or if you somehow modified the template code?

**Comment by blue-freedom-technologies** [comment]
Thank you @JurajSadel for your response. 

We have create a public [repo](https://github.com/blue-freedom-technologies/bug) with the generated code.

We all have ubuntu(s):
![image](https://github.com/esp-rs/esp-hal/assets/142290531/fe318041-63dc-438f-8cbe-54ad4f8fb43f)

Our Rust environment:
![image](https://github.com/esp-rs/esp-hal/assets/142290531/dc4fe3a4-9333-4b59-a9c3-f34aa4551653)

Probably we should upgrade the esp32-c6 firmware ?

Cheers,

**Comment by bjoernQ** [comment]
I guess you are using the USB connector on the right of the dev-board?

In that case it's using serial-jtag and to see the output you would need to choose it for esp-println/esp-backtrace like this
```
esp-backtrace = { version = "0.7.0", features = ["esp32c6", "panic-handler", "exception-handler", "print-jtag-serial"] }
esp-println       = { version = "0.5.0", default-features=false, features = ["esp32c6","jtag_serial"] }
```

Or you can just use the other USB port

**Comment by JurajSadel** [comment]
I tried to run your [linked repo](https://github.com/blue-freedom-technologies/bug) on Ubuntu and it works fine for me. Could you please double-check the connection as @bjoernQ suggested?

**Comment by blue-freedom-technologies** [comment]
Hi @bjoernQ , @JurajSadel 

Yep, we have try that also..

But the result is:
![image](https://github.com/esp-rs/esp-hal/assets/142290531/b30d7863-596d-4b66-bfec-17ecd0c93cbb)

**Comment by JurajSadel** [comment]
Do you use "default" Ubuntu or is it the WSL subsystem?

**Comment by blue-freedom-technologies** [comment]
We all use real Ubuntu(s) no WSL windows subsystems.

**Comment by JurajSadel** [comment]
If you list your USB ports, what does the C6 board look like? `/dev/ttyXXXX`

**Comment by JurajSadel** [comment]
Glad you figured it out! Can this issue be closed now?

**Comment by blue-freedom-technologies** [comment]
@JurajSadel  Yep, we have closed the issue.
