### ISSUE TITLE
Come up with better demonstrations of using the `#[ram]` attribute

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#8]
Our current examples do their job in that they give us CI coverage of this feature, and provide some demonstration of how it can be used. We can likely come up with a more interesting/representative example, however.

This feature was added in #6.

**Comment by bjoernQ** [comment]
After thinking about this for quite a while I have no idea for a more exciting example
But with #112 I guess the example now does a better job at showing the feature to users

@jessebraham  Should be close this now?
