### ISSUE TITLE
RMT driver no longer works for some chips after updating PACs to use `svd2rust` 0.24

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#83]
For whatever reason this update seems to have broken this driver for some of the chips. I have verified it still works on the ESP32-S2, but it has stopped working on the ESP32-C3 and ESP32-S3 for me. I do not have an ESP32 board with a neopixel on it so I cannot test this.

This obviously needs to be fixed.

- [ ] ESP32
- [ ] ESP32-C3
- [x] ESP32-S2
- [ ] ESP32-S3

**Comment by jessebraham** [comment]
@bjoernQ whenever you get a chance would you be able to test the `esp32-hal/examples/hello_rgb.rs` example please?

**Comment by bjoernQ** [comment]
checked on ESP32 ... it lights up three random RGBs in colors that totally don't make sense .... so, I'd say it's broken

**Comment by bjoernQ** [comment]
After some investigation it pretty much looks like a bug in `svd2rust` to me.

https://github.com/rust-embedded/svd2rust/issues/616

**Comment by bjoernQ** [comment]
OK - seems that - `w.ch_tx_thr_event_int_clr::<7>().set_bit() ` is not the same as `w.ch_tx_thr_event_int_clr(7).set_bit()`
I'll look into taking this into account and fix the issue on our side
