### ISSUE TITLE
The `embassy_serial` example seems to be broken

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#850]
This was confirmed on ESP32, possibly affects other chips. Needs more investigation.

**Comment by bjoernQ** [comment]
Looking into it, it might do what the code says. It's just a slightly weird example

Also it's not correct to return a len of 0 if there is no data to receive (  https://docs.rs/embedded-io-async/0.6.0/embedded_io_async/trait.Read.html#tymethod.read )

**Comment by elpiel** [comment]
Yes, it's correct. Receiving over UART is currently not working for ESP32-C3 as well.

PS: Please consider dumping the UART received data in the example as it's not that clear what happens in the receive loop.
