### ISSUE TITLE
Support linking using `lld`

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#865]
- [x] #861
- [x] Add LLD option for all RISC-V chips

**Comment by MabezDev** [comment]
LLD is already the default for RISCV, so I've gone ahead and marked it :)

**Comment by bugadani** [comment]
Just out of curiousity, what will lld give us?

**Comment by MabezDev** [comment]
LLD can ship with the rust toolchain, GCC can't is the main motivation. There are other benefits to LLD like the faster link times. Maybe in the _far_ future, cross-lang LTO for the esp-idf-* stuff.

With the PR merged, this can now be closed though.
