### ISSUE TITLE
Possible race condition in SpiDma transfers

### ISSUE THREAD

**Issue by bugadani** [esp-rs/esp-hal#868]
https://github.com/esp-rs/esp-hal/blob/main/esp-hal-common/src/spi/master.rs#L1340

The DMA sets the `GDMA_OUT_EOF_CHn_INT_ENA` bit after the peripheral starts the transmission. This may result in the future never resolving, if some other code is executed between transmission start and listen start.

Or at least I think this is the case.

**Comment by bjoernQ** [comment]
I think I've seen problem caused by this pattern with the AES peripheral which is faster (with small amounts of data) than we get to creating the future - so it's not just a hypothetical thing

**Comment by bugadani** [comment]
I think I'm hitting this issue or something related with esp-wifi and a spidma-driven display; the display's DmaTxFuture often stops resolving if my mobile is connected to the device's AP.
