### ISSUE TITLE
(Re)add a way to ask which GPIO pin caused an interrupt

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#923]
We had it before but somehow it got lost - without it's very convenient to write a GPIO interrupt handler which is listening on multiple pins

**Comment by noahbliss** [comment]
Total noob working through rust on esp and am ashamed to admit I spent half my day trying to figure out what I was doing wrong haha. Just my $0.02 that this would be extremely helpful. I'm over on the xtensa side of the yard if it makes any difference.

**Comment by bjoernQ** [comment]
Sorry to hear you lost half a day with this - hope we will fix this soon
