### ISSUE TITLE
Switch to embedded-hal version 1.0

### ISSUE THREAD

**Issue by tgross35** [esp-rs/esp-hal#926]
Embedded-hal has hit a RC and is looking for final feedback. It may be worth starting to port the EspressIf crates to help locate any flaws before the final release happens.

See https://github.com/rust-embedded/embedded-hal/issues/177#issuecomment-1805300873

**Comment by Vollbrecht** [comment]
this crate already supports e-hal 1.0 rc 1 as well as e-hal 0.2

**Comment by tgross35** [comment]
Oh, I never noticed the feature. Thanks
