### ISSUE TITLE
Implement Digest traits for SHA

### ISSUE THREAD

**Issue by Natureshadow** [esp-rs/esp-hal#941]
In order to use the hardware-accelerated SHA on ESP32 with external code that accepts implementations of the [digest](https://crates.io/crates/digest) traits, it would be helpful to implement those on the `Sha` struct.

The implementation should probably be behind a `digest` feature flag in order to avoid the dependency if not needed.

**Comment by bjoernQ** [comment]
+1 - we should implement the crypto traits for all crypto-accelerators: https://github.com/RustCrypto/traits

but we will need to do what is worked on in https://github.com/esp-rs/esp-hal/pull/866 for them first
