### ISSUE TITLE
Inconsistent `_stack_start` and `_stack_end` symbol naming

### ISSUE THREAD

**Issue by bugadani** [esp-rs/esp-hal#961]
It seems that on C6, `_stack_end < _stack_start`, whole on S3, `_stack_start_cpu0 < _stack_end_cpu0`.

**Comment by bugadani** [comment]
Eh I guess this is a RISC-V thing where the stack grows upward?

**Comment by MabezDev** [comment]
> In the standard RISC-V calling convention, the stack grows downward and the stack pointer is
always kept 16-byte aligned.

I don't think that's the case :thinking:

**Comment by bugadani** [comment]
The ASSIST_DEBUG examples and the symbol naming both infers this, though. And I'm just feeling around in the dark 🤷‍♂️

**Comment by MabezDev** [comment]
Hmm, lets look into this a bit more then, just to be sure :D.
