### ISSUE TITLE
Allow using `FROM_CPU0` for interrupt executors on single-core MCUs

### ISSUE THREAD

**Issue by bugadani** [esp-rs/esp-hal#969]
i.e. cfg-enable [this line](https://github.com/esp-rs/esp-hal/blob/39519dfdc9124d93180e89c4531b67739fca6146/esp-hal-common/src/embassy/executor/interrupt.rs#L72)

**Comment by MabezDev** [comment]
I believe this has be resolved via https://github.com/esp-rs/esp-hal/pull/1398
