### ISSUE TITLE
Setting MAC addresses

### ISSUE THREAD

**Issue by Natureshadow** [esp-rs/esp-hal#971]
esp-idf supports setting various MAC addresses of interfaces on the ESP. The implementation is here:

https://github.com/espressif/esp-idf/blob/a7fbf452fa181452f266b16c49063e2ff069f119/components/esp_hw_support/mac_addr.c#L127

From a quick glance, it looks quite straightforward (a lookup table for offsets, and a `memcpy` of the MAC address bytes to the correct location), but I don't know enough of esp-hal itself to implement it myself.

It would be great if we could set MAC addresses through esp-hal.

**Comment by Natureshadow** [comment]
I don't quite understand how the PR explains that setting Wifi/BLE addresses is not ESP-specific and out of scope.

How would I set the BLE MAC address, now?

**Comment by Natureshadow** [comment]
Looked at it closer now, and I don't think the linked PR addresses this issue. Most importantly, it seems the implementation only allows burning a MAC address into the efuse, and not changing it temporarily.

So, if this issue gets a `wontfix`, a pointer on how I would do this myself in a project that uses esp32-hal would be helpful.

**Comment by kamirr** [comment]
> Looked at it closer now, and I don't think the linked PR addresses this issue. Most importantly, it seems the implementation only allows burning a MAC address into the efuse, and not changing it temporarily.
> 
> So, if this issue gets a `wontfix`, a pointer on how I would do this myself in a project that uses esp32-hal would be helpful.

Sorry for the late reply. Let me clarify a couple things:
1. My patch does *only* supports overwriting mac temporarily. You physically cannot modify eFuse.
2. The `esp-wifi` crate (which I presume you're using) reads the mac via the API I changed and thus works on the overwritten value. I've verified that this works as expected.

**Comment by Natureshadow** [comment]
>2. The `esp-wifi` crate (which I presume you're using) reads the mac via the API I changed and thus works on the overwritten value. I've verified that this works as expected.

But that will not get me the address I set as the BLE MAC, right? Because the Wifi code will derive a new MAC from it via one of two methods which I have no control over.

**Comment by kamirr** [comment]
> But that will not get me the address I set as the BLE MAC, right? Because the Wifi code will derive a new MAC from it via one of two methods which I have no control over.

I'm confused as to how you'd set the BLE MAC. You can only set what IDF refers to as the `base MAC`. How `esp-wifi` derives MAC addresses for WiFi and BLE is external to `esp-hal`, and I don't exactly remember how it's implemented. If you want more control over that, you should probably open an issue there.

**Comment by Natureshadow** [comment]
Have you read the initial feature request?

It references the respective implementation in esp-idf.

Exactly that is what I want to achieve.

**Comment by kamirr** [comment]
> Have you read the initial feature request? It references the respective implementation in esp-idf. Exactly that is what I want to achieve.

> Have you read the initial feature request? It references the respective implementation in esp-idf. Exactly that is what I want to achieve.

As I've mentioned in the PR which resolved this issue, the MAC address kinds defined by IDF are not actually part of hardware, but a purely software-base abstraction, which cannot exactly be reconstructed in this case, because while IDF integrates with the wifi/ble driver, `esp-hal` does not -- radio communication is external and implemented in a separate crate -- `esp-wifi`.

What exists in hardware is the base MAC, you can overwrite that thus indirectly affecting MAC addresses computed by `esp-wifi`, which computes the derived addresses in a way which we can't control. If you wish to be able to change that, a patch to `esp-wifi` is necessary, this cannot be achieved within `esp-hal`.

**Comment by Natureshadow** [comment]
Hmm, then I get the code in esp-idf, and the relation between esp-hal and es-idf, wrong.
