### ISSUE TITLE
Fix async uart overflow implementation

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#989]
Quote from #977

> The current overflow handling will in some cases return a buffer where there are missing characters (as there was an overflow) and then at the next call to async read(), report that there where an overflow either in the current or the previous async read().

> What I expect we need is a way to have a shared atomic state between the interrupt handler and the non interrupt code.
The interrupt should set the ovf flag as soon as the hardware has reported an overflow.
Async read() would check the flag at least once after reading all bytes from the buffer, but before returning anything to the caller.
Then either both async read() and drain_fifo(), or possibly only one of them could clear the ovf flag in the shared atomic state when they know that it has been reported to the user.

> I did not realize that it was even possible to drain the buffer as the current async read() is not capable of doing that.

> So it is probably better to just re-add the check here and then provide a follow up patch patch to improve ovf handling.

**Comment by mattiasgronlund** [comment]
Certainly that would be a great exercise!

**Comment by konsulten** [comment]
https://github.com/esp-rs/esp-hal/pull/1168

**Comment by MabezDev** [comment]
Closed via https://github.com/esp-rs/esp-hal/pull/1445, thanks again @konsulten!
